# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.1/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/volkhin/esp/volkhin_nixie_timer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/volkhin/esp/volkhin_nixie_timer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.13.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.13.1/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.13.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.13.1/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.13.1/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.13.1/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.1/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/volkhin/esp/volkhin_nixie_timer/CMakeFiles /Users/volkhin/esp/volkhin_nixie_timer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/volkhin/esp/volkhin_nixie_timer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named size-files

# Build rule for target.
size-files: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 size-files
.PHONY : size-files

# fast build rule for target.
size-files/fast:
	$(MAKE) -f CMakeFiles/size-files.dir/build.make CMakeFiles/size-files.dir/build
.PHONY : size-files/fast

#=============================================================================
# Target rules for targets named size-components

# Build rule for target.
size-components: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 size-components
.PHONY : size-components

# fast build rule for target.
size-components/fast:
	$(MAKE) -f CMakeFiles/size-components.dir/build.make CMakeFiles/size-components.dir/build
.PHONY : size-components/fast

#=============================================================================
# Target rules for targets named volkhin_nixie_timer.elf

# Build rule for target.
volkhin_nixie_timer.elf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 volkhin_nixie_timer.elf
.PHONY : volkhin_nixie_timer.elf

# fast build rule for target.
volkhin_nixie_timer.elf/fast:
	$(MAKE) -f CMakeFiles/volkhin_nixie_timer.elf.dir/build.make CMakeFiles/volkhin_nixie_timer.elf.dir/build
.PHONY : volkhin_nixie_timer.elf/fast

#=============================================================================
# Target rules for targets named size

# Build rule for target.
size: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 size
.PHONY : size

# fast build rule for target.
size/fast:
	$(MAKE) -f CMakeFiles/size.dir/build.make CMakeFiles/size.dir/build
.PHONY : size/fast

#=============================================================================
# Target rules for targets named dummy_main_src

# Build rule for target.
dummy_main_src: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dummy_main_src
.PHONY : dummy_main_src

# fast build rule for target.
dummy_main_src/fast:
	$(MAKE) -f CMakeFiles/dummy_main_src.dir/build.make CMakeFiles/dummy_main_src.dir/build
.PHONY : dummy_main_src/fast

#=============================================================================
# Target rules for targets named mconf-idf

# Build rule for target.
mconf-idf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mconf-idf
.PHONY : mconf-idf

# fast build rule for target.
mconf-idf/fast:
	$(MAKE) -f CMakeFiles/mconf-idf.dir/build.make CMakeFiles/mconf-idf.dir/build
.PHONY : mconf-idf/fast

#=============================================================================
# Target rules for targets named bootloader-flash

# Build rule for target.
bootloader-flash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bootloader-flash
.PHONY : bootloader-flash

# fast build rule for target.
bootloader-flash/fast:
	$(MAKE) -f esp-idf/CMakeFiles/bootloader-flash.dir/build.make esp-idf/CMakeFiles/bootloader-flash.dir/build
.PHONY : bootloader-flash/fast

#=============================================================================
# Target rules for targets named app-flash

# Build rule for target.
app-flash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app-flash
.PHONY : app-flash

# fast build rule for target.
app-flash/fast:
	$(MAKE) -f esp-idf/CMakeFiles/app-flash.dir/build.make esp-idf/CMakeFiles/app-flash.dir/build
.PHONY : app-flash/fast

#=============================================================================
# Target rules for targets named flash

# Build rule for target.
flash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flash
.PHONY : flash

# fast build rule for target.
flash/fast:
	$(MAKE) -f esp-idf/CMakeFiles/flash.dir/build.make esp-idf/CMakeFiles/flash.dir/build
.PHONY : flash/fast

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) -f esp-idf/CMakeFiles/app.dir/build.make esp-idf/CMakeFiles/app.dir/build
.PHONY : app/fast

#=============================================================================
# Target rules for targets named ldgen

# Build rule for target.
ldgen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ldgen
.PHONY : ldgen

# fast build rule for target.
ldgen/fast:
	$(MAKE) -f esp-idf/CMakeFiles/ldgen.dir/build.make esp-idf/CMakeFiles/ldgen.dir/build
.PHONY : ldgen/fast

#=============================================================================
# Target rules for targets named bootloader

# Build rule for target.
bootloader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bootloader
.PHONY : bootloader

# fast build rule for target.
bootloader/fast:
	$(MAKE) -f esp-idf/CMakeFiles/bootloader.dir/build.make esp-idf/CMakeFiles/bootloader.dir/build
.PHONY : bootloader/fast

#=============================================================================
# Target rules for targets named gen_secure_boot_signing_key

# Build rule for target.
gen_secure_boot_signing_key: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gen_secure_boot_signing_key
.PHONY : gen_secure_boot_signing_key

# fast build rule for target.
gen_secure_boot_signing_key/fast:
	$(MAKE) -f esp-idf/CMakeFiles/gen_secure_boot_signing_key.dir/build.make esp-idf/CMakeFiles/gen_secure_boot_signing_key.dir/build
.PHONY : gen_secure_boot_signing_key/fast

#=============================================================================
# Target rules for targets named ldgen_section_infos

# Build rule for target.
ldgen_section_infos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ldgen_section_infos
.PHONY : ldgen_section_infos

# fast build rule for target.
ldgen_section_infos/fast:
	$(MAKE) -f esp-idf/CMakeFiles/ldgen_section_infos.dir/build.make esp-idf/CMakeFiles/ldgen_section_infos.dir/build
.PHONY : ldgen_section_infos/fast

#=============================================================================
# Target rules for targets named confserver

# Build rule for target.
confserver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 confserver
.PHONY : confserver

# fast build rule for target.
confserver/fast:
	$(MAKE) -f esp-idf/CMakeFiles/confserver.dir/build.make esp-idf/CMakeFiles/confserver.dir/build
.PHONY : confserver/fast

#=============================================================================
# Target rules for targets named menuconfig

# Build rule for target.
menuconfig: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 menuconfig
.PHONY : menuconfig

# fast build rule for target.
menuconfig/fast:
	$(MAKE) -f esp-idf/CMakeFiles/menuconfig.dir/build.make esp-idf/CMakeFiles/menuconfig.dir/build
.PHONY : menuconfig/fast

#=============================================================================
# Target rules for targets named idf_component_soc_sections_info

# Build rule for target.
idf_component_soc_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_soc_sections_info
.PHONY : idf_component_soc_sections_info

# fast build rule for target.
idf_component_soc_sections_info/fast:
	$(MAKE) -f esp-idf/soc/CMakeFiles/idf_component_soc_sections_info.dir/build.make esp-idf/soc/CMakeFiles/idf_component_soc_sections_info.dir/build
.PHONY : idf_component_soc_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_soc

# Build rule for target.
idf_component_soc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_soc
.PHONY : idf_component_soc

# fast build rule for target.
idf_component_soc/fast:
	$(MAKE) -f esp-idf/soc/CMakeFiles/idf_component_soc.dir/build.make esp-idf/soc/CMakeFiles/idf_component_soc.dir/build
.PHONY : idf_component_soc/fast

#=============================================================================
# Target rules for targets named idf_component_log

# Build rule for target.
idf_component_log: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_log
.PHONY : idf_component_log

# fast build rule for target.
idf_component_log/fast:
	$(MAKE) -f esp-idf/log/CMakeFiles/idf_component_log.dir/build.make esp-idf/log/CMakeFiles/idf_component_log.dir/build
.PHONY : idf_component_log/fast

#=============================================================================
# Target rules for targets named idf_component_log_sections_info

# Build rule for target.
idf_component_log_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_log_sections_info
.PHONY : idf_component_log_sections_info

# fast build rule for target.
idf_component_log_sections_info/fast:
	$(MAKE) -f esp-idf/log/CMakeFiles/idf_component_log_sections_info.dir/build.make esp-idf/log/CMakeFiles/idf_component_log_sections_info.dir/build
.PHONY : idf_component_log_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_heap_sections_info

# Build rule for target.
idf_component_heap_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_heap_sections_info
.PHONY : idf_component_heap_sections_info

# fast build rule for target.
idf_component_heap_sections_info/fast:
	$(MAKE) -f esp-idf/heap/CMakeFiles/idf_component_heap_sections_info.dir/build.make esp-idf/heap/CMakeFiles/idf_component_heap_sections_info.dir/build
.PHONY : idf_component_heap_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_heap

# Build rule for target.
idf_component_heap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_heap
.PHONY : idf_component_heap

# fast build rule for target.
idf_component_heap/fast:
	$(MAKE) -f esp-idf/heap/CMakeFiles/idf_component_heap.dir/build.make esp-idf/heap/CMakeFiles/idf_component_heap.dir/build
.PHONY : idf_component_heap/fast

#=============================================================================
# Target rules for targets named idf_component_xtensa-debug-module

# Build rule for target.
idf_component_xtensa-debug-module: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_xtensa-debug-module
.PHONY : idf_component_xtensa-debug-module

# fast build rule for target.
idf_component_xtensa-debug-module/fast:
	$(MAKE) -f esp-idf/xtensa-debug-module/CMakeFiles/idf_component_xtensa-debug-module.dir/build.make esp-idf/xtensa-debug-module/CMakeFiles/idf_component_xtensa-debug-module.dir/build
.PHONY : idf_component_xtensa-debug-module/fast

#=============================================================================
# Target rules for targets named idf_component_xtensa-debug-module_sections_info

# Build rule for target.
idf_component_xtensa-debug-module_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_xtensa-debug-module_sections_info
.PHONY : idf_component_xtensa-debug-module_sections_info

# fast build rule for target.
idf_component_xtensa-debug-module_sections_info/fast:
	$(MAKE) -f esp-idf/xtensa-debug-module/CMakeFiles/idf_component_xtensa-debug-module_sections_info.dir/build.make esp-idf/xtensa-debug-module/CMakeFiles/idf_component_xtensa-debug-module_sections_info.dir/build
.PHONY : idf_component_xtensa-debug-module_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_app_trace_sections_info

# Build rule for target.
idf_component_app_trace_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_app_trace_sections_info
.PHONY : idf_component_app_trace_sections_info

# fast build rule for target.
idf_component_app_trace_sections_info/fast:
	$(MAKE) -f esp-idf/app_trace/CMakeFiles/idf_component_app_trace_sections_info.dir/build.make esp-idf/app_trace/CMakeFiles/idf_component_app_trace_sections_info.dir/build
.PHONY : idf_component_app_trace_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_app_trace

# Build rule for target.
idf_component_app_trace: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_app_trace
.PHONY : idf_component_app_trace

# fast build rule for target.
idf_component_app_trace/fast:
	$(MAKE) -f esp-idf/app_trace/CMakeFiles/idf_component_app_trace.dir/build.make esp-idf/app_trace/CMakeFiles/idf_component_app_trace.dir/build
.PHONY : idf_component_app_trace/fast

#=============================================================================
# Target rules for targets named idf_component_freertos_sections_info

# Build rule for target.
idf_component_freertos_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_freertos_sections_info
.PHONY : idf_component_freertos_sections_info

# fast build rule for target.
idf_component_freertos_sections_info/fast:
	$(MAKE) -f esp-idf/freertos/CMakeFiles/idf_component_freertos_sections_info.dir/build.make esp-idf/freertos/CMakeFiles/idf_component_freertos_sections_info.dir/build
.PHONY : idf_component_freertos_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_freertos

# Build rule for target.
idf_component_freertos: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_freertos
.PHONY : idf_component_freertos

# fast build rule for target.
idf_component_freertos/fast:
	$(MAKE) -f esp-idf/freertos/CMakeFiles/idf_component_freertos.dir/build.make esp-idf/freertos/CMakeFiles/idf_component_freertos.dir/build
.PHONY : idf_component_freertos/fast

#=============================================================================
# Target rules for targets named idf_component_vfs_sections_info

# Build rule for target.
idf_component_vfs_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_vfs_sections_info
.PHONY : idf_component_vfs_sections_info

# fast build rule for target.
idf_component_vfs_sections_info/fast:
	$(MAKE) -f esp-idf/vfs/CMakeFiles/idf_component_vfs_sections_info.dir/build.make esp-idf/vfs/CMakeFiles/idf_component_vfs_sections_info.dir/build
.PHONY : idf_component_vfs_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_vfs

# Build rule for target.
idf_component_vfs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_vfs
.PHONY : idf_component_vfs

# fast build rule for target.
idf_component_vfs/fast:
	$(MAKE) -f esp-idf/vfs/CMakeFiles/idf_component_vfs.dir/build.make esp-idf/vfs/CMakeFiles/idf_component_vfs.dir/build
.PHONY : idf_component_vfs/fast

#=============================================================================
# Target rules for targets named idf_component_newlib

# Build rule for target.
idf_component_newlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_newlib
.PHONY : idf_component_newlib

# fast build rule for target.
idf_component_newlib/fast:
	$(MAKE) -f esp-idf/newlib/CMakeFiles/idf_component_newlib.dir/build.make esp-idf/newlib/CMakeFiles/idf_component_newlib.dir/build
.PHONY : idf_component_newlib/fast

#=============================================================================
# Target rules for targets named idf_component_newlib_sections_info

# Build rule for target.
idf_component_newlib_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_newlib_sections_info
.PHONY : idf_component_newlib_sections_info

# fast build rule for target.
idf_component_newlib_sections_info/fast:
	$(MAKE) -f esp-idf/newlib/CMakeFiles/idf_component_newlib_sections_info.dir/build.make esp-idf/newlib/CMakeFiles/idf_component_newlib_sections_info.dir/build
.PHONY : idf_component_newlib_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_esp_ringbuf

# Build rule for target.
idf_component_esp_ringbuf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_esp_ringbuf
.PHONY : idf_component_esp_ringbuf

# fast build rule for target.
idf_component_esp_ringbuf/fast:
	$(MAKE) -f esp-idf/esp_ringbuf/CMakeFiles/idf_component_esp_ringbuf.dir/build.make esp-idf/esp_ringbuf/CMakeFiles/idf_component_esp_ringbuf.dir/build
.PHONY : idf_component_esp_ringbuf/fast

#=============================================================================
# Target rules for targets named idf_component_esp_ringbuf_sections_info

# Build rule for target.
idf_component_esp_ringbuf_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_esp_ringbuf_sections_info
.PHONY : idf_component_esp_ringbuf_sections_info

# fast build rule for target.
idf_component_esp_ringbuf_sections_info/fast:
	$(MAKE) -f esp-idf/esp_ringbuf/CMakeFiles/idf_component_esp_ringbuf_sections_info.dir/build.make esp-idf/esp_ringbuf/CMakeFiles/idf_component_esp_ringbuf_sections_info.dir/build
.PHONY : idf_component_esp_ringbuf_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_driver_sections_info

# Build rule for target.
idf_component_driver_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_driver_sections_info
.PHONY : idf_component_driver_sections_info

# fast build rule for target.
idf_component_driver_sections_info/fast:
	$(MAKE) -f esp-idf/driver/CMakeFiles/idf_component_driver_sections_info.dir/build.make esp-idf/driver/CMakeFiles/idf_component_driver_sections_info.dir/build
.PHONY : idf_component_driver_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_driver

# Build rule for target.
idf_component_driver: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_driver
.PHONY : idf_component_driver

# fast build rule for target.
idf_component_driver/fast:
	$(MAKE) -f esp-idf/driver/CMakeFiles/idf_component_driver.dir/build.make esp-idf/driver/CMakeFiles/idf_component_driver.dir/build
.PHONY : idf_component_driver/fast

#=============================================================================
# Target rules for targets named idf_component_esp_event_sections_info

# Build rule for target.
idf_component_esp_event_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_esp_event_sections_info
.PHONY : idf_component_esp_event_sections_info

# fast build rule for target.
idf_component_esp_event_sections_info/fast:
	$(MAKE) -f esp-idf/esp_event/CMakeFiles/idf_component_esp_event_sections_info.dir/build.make esp-idf/esp_event/CMakeFiles/idf_component_esp_event_sections_info.dir/build
.PHONY : idf_component_esp_event_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_esp_event

# Build rule for target.
idf_component_esp_event: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_esp_event
.PHONY : idf_component_esp_event

# fast build rule for target.
idf_component_esp_event/fast:
	$(MAKE) -f esp-idf/esp_event/CMakeFiles/idf_component_esp_event.dir/build.make esp-idf/esp_event/CMakeFiles/idf_component_esp_event.dir/build
.PHONY : idf_component_esp_event/fast

#=============================================================================
# Target rules for targets named idf_component_ethernet_sections_info

# Build rule for target.
idf_component_ethernet_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_ethernet_sections_info
.PHONY : idf_component_ethernet_sections_info

# fast build rule for target.
idf_component_ethernet_sections_info/fast:
	$(MAKE) -f esp-idf/ethernet/CMakeFiles/idf_component_ethernet_sections_info.dir/build.make esp-idf/ethernet/CMakeFiles/idf_component_ethernet_sections_info.dir/build
.PHONY : idf_component_ethernet_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_ethernet

# Build rule for target.
idf_component_ethernet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_ethernet
.PHONY : idf_component_ethernet

# fast build rule for target.
idf_component_ethernet/fast:
	$(MAKE) -f esp-idf/ethernet/CMakeFiles/idf_component_ethernet.dir/build.make esp-idf/ethernet/CMakeFiles/idf_component_ethernet.dir/build
.PHONY : idf_component_ethernet/fast

#=============================================================================
# Target rules for targets named idf_component_mbedtls_sections_info

# Build rule for target.
idf_component_mbedtls_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_mbedtls_sections_info
.PHONY : idf_component_mbedtls_sections_info

# fast build rule for target.
idf_component_mbedtls_sections_info/fast:
	$(MAKE) -f esp-idf/mbedtls/CMakeFiles/idf_component_mbedtls_sections_info.dir/build.make esp-idf/mbedtls/CMakeFiles/idf_component_mbedtls_sections_info.dir/build
.PHONY : idf_component_mbedtls_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_mbedtls

# Build rule for target.
idf_component_mbedtls: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_mbedtls
.PHONY : idf_component_mbedtls

# fast build rule for target.
idf_component_mbedtls/fast:
	$(MAKE) -f esp-idf/mbedtls/CMakeFiles/idf_component_mbedtls.dir/build.make esp-idf/mbedtls/CMakeFiles/idf_component_mbedtls.dir/build
.PHONY : idf_component_mbedtls/fast

#=============================================================================
# Target rules for targets named apidoc

# Build rule for target.
apidoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 apidoc
.PHONY : apidoc

# fast build rule for target.
apidoc/fast:
	$(MAKE) -f esp-idf/mbedtls/mbedtls/CMakeFiles/apidoc.dir/build.make esp-idf/mbedtls/mbedtls/CMakeFiles/apidoc.dir/build
.PHONY : apidoc/fast

#=============================================================================
# Target rules for targets named lib

# Build rule for target.
lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lib
.PHONY : lib

# fast build rule for target.
lib/fast:
	$(MAKE) -f esp-idf/mbedtls/mbedtls/library/CMakeFiles/lib.dir/build.make esp-idf/mbedtls/mbedtls/library/CMakeFiles/lib.dir/build
.PHONY : lib/fast

#=============================================================================
# Target rules for targets named mbedcrypto

# Build rule for target.
mbedcrypto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mbedcrypto
.PHONY : mbedcrypto

# fast build rule for target.
mbedcrypto/fast:
	$(MAKE) -f esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/build.make esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedcrypto.dir/build
.PHONY : mbedcrypto/fast

#=============================================================================
# Target rules for targets named mbedx509

# Build rule for target.
mbedx509: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mbedx509
.PHONY : mbedx509

# fast build rule for target.
mbedx509/fast:
	$(MAKE) -f esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedx509.dir/build.make esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedx509.dir/build
.PHONY : mbedx509/fast

#=============================================================================
# Target rules for targets named mbedtls

# Build rule for target.
mbedtls: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mbedtls
.PHONY : mbedtls

# fast build rule for target.
mbedtls/fast:
	$(MAKE) -f esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedtls.dir/build.make esp-idf/mbedtls/mbedtls/library/CMakeFiles/mbedtls.dir/build
.PHONY : mbedtls/fast

#=============================================================================
# Target rules for targets named idf_component_micro-ecc_sections_info

# Build rule for target.
idf_component_micro-ecc_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_micro-ecc_sections_info
.PHONY : idf_component_micro-ecc_sections_info

# fast build rule for target.
idf_component_micro-ecc_sections_info/fast:
	$(MAKE) -f esp-idf/micro-ecc/CMakeFiles/idf_component_micro-ecc_sections_info.dir/build.make esp-idf/micro-ecc/CMakeFiles/idf_component_micro-ecc_sections_info.dir/build
.PHONY : idf_component_micro-ecc_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_micro-ecc

# Build rule for target.
idf_component_micro-ecc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_micro-ecc
.PHONY : idf_component_micro-ecc

# fast build rule for target.
idf_component_micro-ecc/fast:
	$(MAKE) -f esp-idf/micro-ecc/CMakeFiles/idf_component_micro-ecc.dir/build.make esp-idf/micro-ecc/CMakeFiles/idf_component_micro-ecc.dir/build
.PHONY : idf_component_micro-ecc/fast

#=============================================================================
# Target rules for targets named idf_component_bootloader_support_sections_info

# Build rule for target.
idf_component_bootloader_support_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_bootloader_support_sections_info
.PHONY : idf_component_bootloader_support_sections_info

# fast build rule for target.
idf_component_bootloader_support_sections_info/fast:
	$(MAKE) -f esp-idf/bootloader_support/CMakeFiles/idf_component_bootloader_support_sections_info.dir/build.make esp-idf/bootloader_support/CMakeFiles/idf_component_bootloader_support_sections_info.dir/build
.PHONY : idf_component_bootloader_support_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_bootloader_support

# Build rule for target.
idf_component_bootloader_support: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_bootloader_support
.PHONY : idf_component_bootloader_support

# fast build rule for target.
idf_component_bootloader_support/fast:
	$(MAKE) -f esp-idf/bootloader_support/CMakeFiles/idf_component_bootloader_support.dir/build.make esp-idf/bootloader_support/CMakeFiles/idf_component_bootloader_support.dir/build
.PHONY : idf_component_bootloader_support/fast

#=============================================================================
# Target rules for targets named partition_table

# Build rule for target.
partition_table: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 partition_table
.PHONY : partition_table

# fast build rule for target.
partition_table/fast:
	$(MAKE) -f esp-idf/partition_table/CMakeFiles/partition_table.dir/build.make esp-idf/partition_table/CMakeFiles/partition_table.dir/build
.PHONY : partition_table/fast

#=============================================================================
# Target rules for targets named erase_otadata

# Build rule for target.
erase_otadata: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 erase_otadata
.PHONY : erase_otadata

# fast build rule for target.
erase_otadata/fast:
	$(MAKE) -f esp-idf/app_update/CMakeFiles/erase_otadata.dir/build.make esp-idf/app_update/CMakeFiles/erase_otadata.dir/build
.PHONY : erase_otadata/fast

#=============================================================================
# Target rules for targets named read_otadata

# Build rule for target.
read_otadata: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 read_otadata
.PHONY : read_otadata

# fast build rule for target.
read_otadata/fast:
	$(MAKE) -f esp-idf/app_update/CMakeFiles/read_otadata.dir/build.make esp-idf/app_update/CMakeFiles/read_otadata.dir/build
.PHONY : read_otadata/fast

#=============================================================================
# Target rules for targets named idf_component_app_update_sections_info

# Build rule for target.
idf_component_app_update_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_app_update_sections_info
.PHONY : idf_component_app_update_sections_info

# fast build rule for target.
idf_component_app_update_sections_info/fast:
	$(MAKE) -f esp-idf/app_update/CMakeFiles/idf_component_app_update_sections_info.dir/build.make esp-idf/app_update/CMakeFiles/idf_component_app_update_sections_info.dir/build
.PHONY : idf_component_app_update_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_app_update

# Build rule for target.
idf_component_app_update: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_app_update
.PHONY : idf_component_app_update

# fast build rule for target.
idf_component_app_update/fast:
	$(MAKE) -f esp-idf/app_update/CMakeFiles/idf_component_app_update.dir/build.make esp-idf/app_update/CMakeFiles/idf_component_app_update.dir/build
.PHONY : idf_component_app_update/fast

#=============================================================================
# Target rules for targets named idf_component_spi_flash

# Build rule for target.
idf_component_spi_flash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_spi_flash
.PHONY : idf_component_spi_flash

# fast build rule for target.
idf_component_spi_flash/fast:
	$(MAKE) -f esp-idf/spi_flash/CMakeFiles/idf_component_spi_flash.dir/build.make esp-idf/spi_flash/CMakeFiles/idf_component_spi_flash.dir/build
.PHONY : idf_component_spi_flash/fast

#=============================================================================
# Target rules for targets named idf_component_spi_flash_sections_info

# Build rule for target.
idf_component_spi_flash_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_spi_flash_sections_info
.PHONY : idf_component_spi_flash_sections_info

# fast build rule for target.
idf_component_spi_flash_sections_info/fast:
	$(MAKE) -f esp-idf/spi_flash/CMakeFiles/idf_component_spi_flash_sections_info.dir/build.make esp-idf/spi_flash/CMakeFiles/idf_component_spi_flash_sections_info.dir/build
.PHONY : idf_component_spi_flash_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_nvs_flash

# Build rule for target.
idf_component_nvs_flash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_nvs_flash
.PHONY : idf_component_nvs_flash

# fast build rule for target.
idf_component_nvs_flash/fast:
	$(MAKE) -f esp-idf/nvs_flash/CMakeFiles/idf_component_nvs_flash.dir/build.make esp-idf/nvs_flash/CMakeFiles/idf_component_nvs_flash.dir/build
.PHONY : idf_component_nvs_flash/fast

#=============================================================================
# Target rules for targets named idf_component_nvs_flash_sections_info

# Build rule for target.
idf_component_nvs_flash_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_nvs_flash_sections_info
.PHONY : idf_component_nvs_flash_sections_info

# fast build rule for target.
idf_component_nvs_flash_sections_info/fast:
	$(MAKE) -f esp-idf/nvs_flash/CMakeFiles/idf_component_nvs_flash_sections_info.dir/build.make esp-idf/nvs_flash/CMakeFiles/idf_component_nvs_flash_sections_info.dir/build
.PHONY : idf_component_nvs_flash_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_lwip_sections_info

# Build rule for target.
idf_component_lwip_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_lwip_sections_info
.PHONY : idf_component_lwip_sections_info

# fast build rule for target.
idf_component_lwip_sections_info/fast:
	$(MAKE) -f esp-idf/lwip/CMakeFiles/idf_component_lwip_sections_info.dir/build.make esp-idf/lwip/CMakeFiles/idf_component_lwip_sections_info.dir/build
.PHONY : idf_component_lwip_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_lwip

# Build rule for target.
idf_component_lwip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_lwip
.PHONY : idf_component_lwip

# fast build rule for target.
idf_component_lwip/fast:
	$(MAKE) -f esp-idf/lwip/CMakeFiles/idf_component_lwip.dir/build.make esp-idf/lwip/CMakeFiles/idf_component_lwip.dir/build
.PHONY : idf_component_lwip/fast

#=============================================================================
# Target rules for targets named idf_component_tcpip_adapter_sections_info

# Build rule for target.
idf_component_tcpip_adapter_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_tcpip_adapter_sections_info
.PHONY : idf_component_tcpip_adapter_sections_info

# fast build rule for target.
idf_component_tcpip_adapter_sections_info/fast:
	$(MAKE) -f esp-idf/tcpip_adapter/CMakeFiles/idf_component_tcpip_adapter_sections_info.dir/build.make esp-idf/tcpip_adapter/CMakeFiles/idf_component_tcpip_adapter_sections_info.dir/build
.PHONY : idf_component_tcpip_adapter_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_tcpip_adapter

# Build rule for target.
idf_component_tcpip_adapter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_tcpip_adapter
.PHONY : idf_component_tcpip_adapter

# fast build rule for target.
idf_component_tcpip_adapter/fast:
	$(MAKE) -f esp-idf/tcpip_adapter/CMakeFiles/idf_component_tcpip_adapter.dir/build.make esp-idf/tcpip_adapter/CMakeFiles/idf_component_tcpip_adapter.dir/build
.PHONY : idf_component_tcpip_adapter/fast

#=============================================================================
# Target rules for targets named idf_component_pthread_sections_info

# Build rule for target.
idf_component_pthread_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_pthread_sections_info
.PHONY : idf_component_pthread_sections_info

# fast build rule for target.
idf_component_pthread_sections_info/fast:
	$(MAKE) -f esp-idf/pthread/CMakeFiles/idf_component_pthread_sections_info.dir/build.make esp-idf/pthread/CMakeFiles/idf_component_pthread_sections_info.dir/build
.PHONY : idf_component_pthread_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_pthread

# Build rule for target.
idf_component_pthread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_pthread
.PHONY : idf_component_pthread

# fast build rule for target.
idf_component_pthread/fast:
	$(MAKE) -f esp-idf/pthread/CMakeFiles/idf_component_pthread.dir/build.make esp-idf/pthread/CMakeFiles/idf_component_pthread.dir/build
.PHONY : idf_component_pthread/fast

#=============================================================================
# Target rules for targets named idf_component_smartconfig_ack

# Build rule for target.
idf_component_smartconfig_ack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_smartconfig_ack
.PHONY : idf_component_smartconfig_ack

# fast build rule for target.
idf_component_smartconfig_ack/fast:
	$(MAKE) -f esp-idf/smartconfig_ack/CMakeFiles/idf_component_smartconfig_ack.dir/build.make esp-idf/smartconfig_ack/CMakeFiles/idf_component_smartconfig_ack.dir/build
.PHONY : idf_component_smartconfig_ack/fast

#=============================================================================
# Target rules for targets named idf_component_smartconfig_ack_sections_info

# Build rule for target.
idf_component_smartconfig_ack_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_smartconfig_ack_sections_info
.PHONY : idf_component_smartconfig_ack_sections_info

# fast build rule for target.
idf_component_smartconfig_ack_sections_info/fast:
	$(MAKE) -f esp-idf/smartconfig_ack/CMakeFiles/idf_component_smartconfig_ack_sections_info.dir/build.make esp-idf/smartconfig_ack/CMakeFiles/idf_component_smartconfig_ack_sections_info.dir/build
.PHONY : idf_component_smartconfig_ack_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_wpa_supplicant_sections_info

# Build rule for target.
idf_component_wpa_supplicant_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_wpa_supplicant_sections_info
.PHONY : idf_component_wpa_supplicant_sections_info

# fast build rule for target.
idf_component_wpa_supplicant_sections_info/fast:
	$(MAKE) -f esp-idf/wpa_supplicant/CMakeFiles/idf_component_wpa_supplicant_sections_info.dir/build.make esp-idf/wpa_supplicant/CMakeFiles/idf_component_wpa_supplicant_sections_info.dir/build
.PHONY : idf_component_wpa_supplicant_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_wpa_supplicant

# Build rule for target.
idf_component_wpa_supplicant: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_wpa_supplicant
.PHONY : idf_component_wpa_supplicant

# fast build rule for target.
idf_component_wpa_supplicant/fast:
	$(MAKE) -f esp-idf/wpa_supplicant/CMakeFiles/idf_component_wpa_supplicant.dir/build.make esp-idf/wpa_supplicant/CMakeFiles/idf_component_wpa_supplicant.dir/build
.PHONY : idf_component_wpa_supplicant/fast

#=============================================================================
# Target rules for targets named idf_component_esp32

# Build rule for target.
idf_component_esp32: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_esp32
.PHONY : idf_component_esp32

# fast build rule for target.
idf_component_esp32/fast:
	$(MAKE) -f esp-idf/esp32/CMakeFiles/idf_component_esp32.dir/build.make esp-idf/esp32/CMakeFiles/idf_component_esp32.dir/build
.PHONY : idf_component_esp32/fast

#=============================================================================
# Target rules for targets named ldgen_esp32.common.ld_script

# Build rule for target.
ldgen_esp32.common.ld_script: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ldgen_esp32.common.ld_script
.PHONY : ldgen_esp32.common.ld_script

# fast build rule for target.
ldgen_esp32.common.ld_script/fast:
	$(MAKE) -f esp-idf/esp32/CMakeFiles/ldgen_esp32.common.ld_script.dir/build.make esp-idf/esp32/CMakeFiles/ldgen_esp32.common.ld_script.dir/build
.PHONY : ldgen_esp32.common.ld_script/fast

#=============================================================================
# Target rules for targets named idf_component_esp32_sections_info

# Build rule for target.
idf_component_esp32_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_esp32_sections_info
.PHONY : idf_component_esp32_sections_info

# fast build rule for target.
idf_component_esp32_sections_info/fast:
	$(MAKE) -f esp-idf/esp32/CMakeFiles/idf_component_esp32_sections_info.dir/build.make esp-idf/esp32/CMakeFiles/idf_component_esp32_sections_info.dir/build
.PHONY : idf_component_esp32_sections_info/fast

#=============================================================================
# Target rules for targets named esp32_linker_script

# Build rule for target.
esp32_linker_script: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 esp32_linker_script
.PHONY : esp32_linker_script

# fast build rule for target.
esp32_linker_script/fast:
	$(MAKE) -f esp-idf/esp32/CMakeFiles/esp32_linker_script.dir/build.make esp-idf/esp32/CMakeFiles/esp32_linker_script.dir/build
.PHONY : esp32_linker_script/fast

#=============================================================================
# Target rules for targets named idf_component_cxx_sections_info

# Build rule for target.
idf_component_cxx_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_cxx_sections_info
.PHONY : idf_component_cxx_sections_info

# fast build rule for target.
idf_component_cxx_sections_info/fast:
	$(MAKE) -f esp-idf/cxx/CMakeFiles/idf_component_cxx_sections_info.dir/build.make esp-idf/cxx/CMakeFiles/idf_component_cxx_sections_info.dir/build
.PHONY : idf_component_cxx_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_cxx

# Build rule for target.
idf_component_cxx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_cxx
.PHONY : idf_component_cxx

# fast build rule for target.
idf_component_cxx/fast:
	$(MAKE) -f esp-idf/cxx/CMakeFiles/idf_component_cxx.dir/build.make esp-idf/cxx/CMakeFiles/idf_component_cxx.dir/build
.PHONY : idf_component_cxx/fast

#=============================================================================
# Target rules for targets named idf_component_asio_sections_info

# Build rule for target.
idf_component_asio_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_asio_sections_info
.PHONY : idf_component_asio_sections_info

# fast build rule for target.
idf_component_asio_sections_info/fast:
	$(MAKE) -f esp-idf/asio/CMakeFiles/idf_component_asio_sections_info.dir/build.make esp-idf/asio/CMakeFiles/idf_component_asio_sections_info.dir/build
.PHONY : idf_component_asio_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_asio

# Build rule for target.
idf_component_asio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_asio
.PHONY : idf_component_asio

# fast build rule for target.
idf_component_asio/fast:
	$(MAKE) -f esp-idf/asio/CMakeFiles/idf_component_asio.dir/build.make esp-idf/asio/CMakeFiles/idf_component_asio.dir/build
.PHONY : idf_component_asio/fast

#=============================================================================
# Target rules for targets named idf_component_jsmn_sections_info

# Build rule for target.
idf_component_jsmn_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_jsmn_sections_info
.PHONY : idf_component_jsmn_sections_info

# fast build rule for target.
idf_component_jsmn_sections_info/fast:
	$(MAKE) -f esp-idf/jsmn/CMakeFiles/idf_component_jsmn_sections_info.dir/build.make esp-idf/jsmn/CMakeFiles/idf_component_jsmn_sections_info.dir/build
.PHONY : idf_component_jsmn_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_jsmn

# Build rule for target.
idf_component_jsmn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_jsmn
.PHONY : idf_component_jsmn

# fast build rule for target.
idf_component_jsmn/fast:
	$(MAKE) -f esp-idf/jsmn/CMakeFiles/idf_component_jsmn.dir/build.make esp-idf/jsmn/CMakeFiles/idf_component_jsmn.dir/build
.PHONY : idf_component_jsmn/fast

#=============================================================================
# Target rules for targets named idf_component_bt

# Build rule for target.
idf_component_bt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_bt
.PHONY : idf_component_bt

# fast build rule for target.
idf_component_bt/fast:
	$(MAKE) -f esp-idf/bt/CMakeFiles/idf_component_bt.dir/build.make esp-idf/bt/CMakeFiles/idf_component_bt.dir/build
.PHONY : idf_component_bt/fast

#=============================================================================
# Target rules for targets named idf_component_bt_sections_info

# Build rule for target.
idf_component_bt_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_bt_sections_info
.PHONY : idf_component_bt_sections_info

# fast build rule for target.
idf_component_bt_sections_info/fast:
	$(MAKE) -f esp-idf/bt/CMakeFiles/idf_component_bt_sections_info.dir/build.make esp-idf/bt/CMakeFiles/idf_component_bt_sections_info.dir/build
.PHONY : idf_component_bt_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_coap_sections_info

# Build rule for target.
idf_component_coap_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_coap_sections_info
.PHONY : idf_component_coap_sections_info

# fast build rule for target.
idf_component_coap_sections_info/fast:
	$(MAKE) -f esp-idf/coap/CMakeFiles/idf_component_coap_sections_info.dir/build.make esp-idf/coap/CMakeFiles/idf_component_coap_sections_info.dir/build
.PHONY : idf_component_coap_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_coap

# Build rule for target.
idf_component_coap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_coap
.PHONY : idf_component_coap

# fast build rule for target.
idf_component_coap/fast:
	$(MAKE) -f esp-idf/coap/CMakeFiles/idf_component_coap.dir/build.make esp-idf/coap/CMakeFiles/idf_component_coap.dir/build
.PHONY : idf_component_coap/fast

#=============================================================================
# Target rules for targets named idf_component_console_sections_info

# Build rule for target.
idf_component_console_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_console_sections_info
.PHONY : idf_component_console_sections_info

# fast build rule for target.
idf_component_console_sections_info/fast:
	$(MAKE) -f esp-idf/console/CMakeFiles/idf_component_console_sections_info.dir/build.make esp-idf/console/CMakeFiles/idf_component_console_sections_info.dir/build
.PHONY : idf_component_console_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_console

# Build rule for target.
idf_component_console: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_console
.PHONY : idf_component_console

# fast build rule for target.
idf_component_console/fast:
	$(MAKE) -f esp-idf/console/CMakeFiles/idf_component_console.dir/build.make esp-idf/console/CMakeFiles/idf_component_console.dir/build
.PHONY : idf_component_console/fast

#=============================================================================
# Target rules for targets named idf_component_nghttp_sections_info

# Build rule for target.
idf_component_nghttp_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_nghttp_sections_info
.PHONY : idf_component_nghttp_sections_info

# fast build rule for target.
idf_component_nghttp_sections_info/fast:
	$(MAKE) -f esp-idf/nghttp/CMakeFiles/idf_component_nghttp_sections_info.dir/build.make esp-idf/nghttp/CMakeFiles/idf_component_nghttp_sections_info.dir/build
.PHONY : idf_component_nghttp_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_nghttp

# Build rule for target.
idf_component_nghttp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_nghttp
.PHONY : idf_component_nghttp

# fast build rule for target.
idf_component_nghttp/fast:
	$(MAKE) -f esp-idf/nghttp/CMakeFiles/idf_component_nghttp.dir/build.make esp-idf/nghttp/CMakeFiles/idf_component_nghttp.dir/build
.PHONY : idf_component_nghttp/fast

#=============================================================================
# Target rules for targets named idf_component_esp-tls_sections_info

# Build rule for target.
idf_component_esp-tls_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_esp-tls_sections_info
.PHONY : idf_component_esp-tls_sections_info

# fast build rule for target.
idf_component_esp-tls_sections_info/fast:
	$(MAKE) -f esp-idf/esp-tls/CMakeFiles/idf_component_esp-tls_sections_info.dir/build.make esp-idf/esp-tls/CMakeFiles/idf_component_esp-tls_sections_info.dir/build
.PHONY : idf_component_esp-tls_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_esp-tls

# Build rule for target.
idf_component_esp-tls: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_esp-tls
.PHONY : idf_component_esp-tls

# fast build rule for target.
idf_component_esp-tls/fast:
	$(MAKE) -f esp-idf/esp-tls/CMakeFiles/idf_component_esp-tls.dir/build.make esp-idf/esp-tls/CMakeFiles/idf_component_esp-tls.dir/build
.PHONY : idf_component_esp-tls/fast

#=============================================================================
# Target rules for targets named idf_component_esp_adc_cal

# Build rule for target.
idf_component_esp_adc_cal: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_esp_adc_cal
.PHONY : idf_component_esp_adc_cal

# fast build rule for target.
idf_component_esp_adc_cal/fast:
	$(MAKE) -f esp-idf/esp_adc_cal/CMakeFiles/idf_component_esp_adc_cal.dir/build.make esp-idf/esp_adc_cal/CMakeFiles/idf_component_esp_adc_cal.dir/build
.PHONY : idf_component_esp_adc_cal/fast

#=============================================================================
# Target rules for targets named idf_component_esp_adc_cal_sections_info

# Build rule for target.
idf_component_esp_adc_cal_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_esp_adc_cal_sections_info
.PHONY : idf_component_esp_adc_cal_sections_info

# fast build rule for target.
idf_component_esp_adc_cal_sections_info/fast:
	$(MAKE) -f esp-idf/esp_adc_cal/CMakeFiles/idf_component_esp_adc_cal_sections_info.dir/build.make esp-idf/esp_adc_cal/CMakeFiles/idf_component_esp_adc_cal_sections_info.dir/build
.PHONY : idf_component_esp_adc_cal_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_tcp_transport

# Build rule for target.
idf_component_tcp_transport: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_tcp_transport
.PHONY : idf_component_tcp_transport

# fast build rule for target.
idf_component_tcp_transport/fast:
	$(MAKE) -f esp-idf/tcp_transport/CMakeFiles/idf_component_tcp_transport.dir/build.make esp-idf/tcp_transport/CMakeFiles/idf_component_tcp_transport.dir/build
.PHONY : idf_component_tcp_transport/fast

#=============================================================================
# Target rules for targets named idf_component_tcp_transport_sections_info

# Build rule for target.
idf_component_tcp_transport_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_tcp_transport_sections_info
.PHONY : idf_component_tcp_transport_sections_info

# fast build rule for target.
idf_component_tcp_transport_sections_info/fast:
	$(MAKE) -f esp-idf/tcp_transport/CMakeFiles/idf_component_tcp_transport_sections_info.dir/build.make esp-idf/tcp_transport/CMakeFiles/idf_component_tcp_transport_sections_info.dir/build
.PHONY : idf_component_tcp_transport_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_esp_http_client_sections_info

# Build rule for target.
idf_component_esp_http_client_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_esp_http_client_sections_info
.PHONY : idf_component_esp_http_client_sections_info

# fast build rule for target.
idf_component_esp_http_client_sections_info/fast:
	$(MAKE) -f esp-idf/esp_http_client/CMakeFiles/idf_component_esp_http_client_sections_info.dir/build.make esp-idf/esp_http_client/CMakeFiles/idf_component_esp_http_client_sections_info.dir/build
.PHONY : idf_component_esp_http_client_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_esp_http_client

# Build rule for target.
idf_component_esp_http_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_esp_http_client
.PHONY : idf_component_esp_http_client

# fast build rule for target.
idf_component_esp_http_client/fast:
	$(MAKE) -f esp-idf/esp_http_client/CMakeFiles/idf_component_esp_http_client.dir/build.make esp-idf/esp_http_client/CMakeFiles/idf_component_esp_http_client.dir/build
.PHONY : idf_component_esp_http_client/fast

#=============================================================================
# Target rules for targets named idf_component_esp_http_server

# Build rule for target.
idf_component_esp_http_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_esp_http_server
.PHONY : idf_component_esp_http_server

# fast build rule for target.
idf_component_esp_http_server/fast:
	$(MAKE) -f esp-idf/esp_http_server/CMakeFiles/idf_component_esp_http_server.dir/build.make esp-idf/esp_http_server/CMakeFiles/idf_component_esp_http_server.dir/build
.PHONY : idf_component_esp_http_server/fast

#=============================================================================
# Target rules for targets named idf_component_esp_http_server_sections_info

# Build rule for target.
idf_component_esp_http_server_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_esp_http_server_sections_info
.PHONY : idf_component_esp_http_server_sections_info

# fast build rule for target.
idf_component_esp_http_server_sections_info/fast:
	$(MAKE) -f esp-idf/esp_http_server/CMakeFiles/idf_component_esp_http_server_sections_info.dir/build.make esp-idf/esp_http_server/CMakeFiles/idf_component_esp_http_server_sections_info.dir/build
.PHONY : idf_component_esp_http_server_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_esp_https_ota_sections_info

# Build rule for target.
idf_component_esp_https_ota_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_esp_https_ota_sections_info
.PHONY : idf_component_esp_https_ota_sections_info

# fast build rule for target.
idf_component_esp_https_ota_sections_info/fast:
	$(MAKE) -f esp-idf/esp_https_ota/CMakeFiles/idf_component_esp_https_ota_sections_info.dir/build.make esp-idf/esp_https_ota/CMakeFiles/idf_component_esp_https_ota_sections_info.dir/build
.PHONY : idf_component_esp_https_ota_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_esp_https_ota

# Build rule for target.
idf_component_esp_https_ota: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_esp_https_ota
.PHONY : idf_component_esp_https_ota

# fast build rule for target.
idf_component_esp_https_ota/fast:
	$(MAKE) -f esp-idf/esp_https_ota/CMakeFiles/idf_component_esp_https_ota.dir/build.make esp-idf/esp_https_ota/CMakeFiles/idf_component_esp_https_ota.dir/build
.PHONY : idf_component_esp_https_ota/fast

#=============================================================================
# Target rules for targets named idf_component_openssl_sections_info

# Build rule for target.
idf_component_openssl_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_openssl_sections_info
.PHONY : idf_component_openssl_sections_info

# fast build rule for target.
idf_component_openssl_sections_info/fast:
	$(MAKE) -f esp-idf/openssl/CMakeFiles/idf_component_openssl_sections_info.dir/build.make esp-idf/openssl/CMakeFiles/idf_component_openssl_sections_info.dir/build
.PHONY : idf_component_openssl_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_openssl

# Build rule for target.
idf_component_openssl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_openssl
.PHONY : idf_component_openssl

# fast build rule for target.
idf_component_openssl/fast:
	$(MAKE) -f esp-idf/openssl/CMakeFiles/idf_component_openssl.dir/build.make esp-idf/openssl/CMakeFiles/idf_component_openssl.dir/build
.PHONY : idf_component_openssl/fast

#=============================================================================
# Target rules for targets named idf_component_esp_https_server_sections_info

# Build rule for target.
idf_component_esp_https_server_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_esp_https_server_sections_info
.PHONY : idf_component_esp_https_server_sections_info

# fast build rule for target.
idf_component_esp_https_server_sections_info/fast:
	$(MAKE) -f esp-idf/esp_https_server/CMakeFiles/idf_component_esp_https_server_sections_info.dir/build.make esp-idf/esp_https_server/CMakeFiles/idf_component_esp_https_server_sections_info.dir/build
.PHONY : idf_component_esp_https_server_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_esp_https_server

# Build rule for target.
idf_component_esp_https_server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_esp_https_server
.PHONY : idf_component_esp_https_server

# fast build rule for target.
idf_component_esp_https_server/fast:
	$(MAKE) -f esp-idf/esp_https_server/CMakeFiles/idf_component_esp_https_server.dir/build.make esp-idf/esp_https_server/CMakeFiles/idf_component_esp_https_server.dir/build
.PHONY : idf_component_esp_https_server/fast

#=============================================================================
# Target rules for targets named idf_component_expat_sections_info

# Build rule for target.
idf_component_expat_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_expat_sections_info
.PHONY : idf_component_expat_sections_info

# fast build rule for target.
idf_component_expat_sections_info/fast:
	$(MAKE) -f esp-idf/expat/CMakeFiles/idf_component_expat_sections_info.dir/build.make esp-idf/expat/CMakeFiles/idf_component_expat_sections_info.dir/build
.PHONY : idf_component_expat_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_expat

# Build rule for target.
idf_component_expat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_expat
.PHONY : idf_component_expat

# fast build rule for target.
idf_component_expat/fast:
	$(MAKE) -f esp-idf/expat/CMakeFiles/idf_component_expat.dir/build.make esp-idf/expat/CMakeFiles/idf_component_expat.dir/build
.PHONY : idf_component_expat/fast

#=============================================================================
# Target rules for targets named idf_component_wear_levelling_sections_info

# Build rule for target.
idf_component_wear_levelling_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_wear_levelling_sections_info
.PHONY : idf_component_wear_levelling_sections_info

# fast build rule for target.
idf_component_wear_levelling_sections_info/fast:
	$(MAKE) -f esp-idf/wear_levelling/CMakeFiles/idf_component_wear_levelling_sections_info.dir/build.make esp-idf/wear_levelling/CMakeFiles/idf_component_wear_levelling_sections_info.dir/build
.PHONY : idf_component_wear_levelling_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_wear_levelling

# Build rule for target.
idf_component_wear_levelling: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_wear_levelling
.PHONY : idf_component_wear_levelling

# fast build rule for target.
idf_component_wear_levelling/fast:
	$(MAKE) -f esp-idf/wear_levelling/CMakeFiles/idf_component_wear_levelling.dir/build.make esp-idf/wear_levelling/CMakeFiles/idf_component_wear_levelling.dir/build
.PHONY : idf_component_wear_levelling/fast

#=============================================================================
# Target rules for targets named idf_component_sdmmc_sections_info

# Build rule for target.
idf_component_sdmmc_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_sdmmc_sections_info
.PHONY : idf_component_sdmmc_sections_info

# fast build rule for target.
idf_component_sdmmc_sections_info/fast:
	$(MAKE) -f esp-idf/sdmmc/CMakeFiles/idf_component_sdmmc_sections_info.dir/build.make esp-idf/sdmmc/CMakeFiles/idf_component_sdmmc_sections_info.dir/build
.PHONY : idf_component_sdmmc_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_sdmmc

# Build rule for target.
idf_component_sdmmc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_sdmmc
.PHONY : idf_component_sdmmc

# fast build rule for target.
idf_component_sdmmc/fast:
	$(MAKE) -f esp-idf/sdmmc/CMakeFiles/idf_component_sdmmc.dir/build.make esp-idf/sdmmc/CMakeFiles/idf_component_sdmmc.dir/build
.PHONY : idf_component_sdmmc/fast

#=============================================================================
# Target rules for targets named idf_component_fatfs

# Build rule for target.
idf_component_fatfs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_fatfs
.PHONY : idf_component_fatfs

# fast build rule for target.
idf_component_fatfs/fast:
	$(MAKE) -f esp-idf/fatfs/CMakeFiles/idf_component_fatfs.dir/build.make esp-idf/fatfs/CMakeFiles/idf_component_fatfs.dir/build
.PHONY : idf_component_fatfs/fast

#=============================================================================
# Target rules for targets named idf_component_fatfs_sections_info

# Build rule for target.
idf_component_fatfs_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_fatfs_sections_info
.PHONY : idf_component_fatfs_sections_info

# fast build rule for target.
idf_component_fatfs_sections_info/fast:
	$(MAKE) -f esp-idf/fatfs/CMakeFiles/idf_component_fatfs_sections_info.dir/build.make esp-idf/fatfs/CMakeFiles/idf_component_fatfs_sections_info.dir/build
.PHONY : idf_component_fatfs_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_freemodbus

# Build rule for target.
idf_component_freemodbus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_freemodbus
.PHONY : idf_component_freemodbus

# fast build rule for target.
idf_component_freemodbus/fast:
	$(MAKE) -f esp-idf/freemodbus/CMakeFiles/idf_component_freemodbus.dir/build.make esp-idf/freemodbus/CMakeFiles/idf_component_freemodbus.dir/build
.PHONY : idf_component_freemodbus/fast

#=============================================================================
# Target rules for targets named idf_component_freemodbus_sections_info

# Build rule for target.
idf_component_freemodbus_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_freemodbus_sections_info
.PHONY : idf_component_freemodbus_sections_info

# fast build rule for target.
idf_component_freemodbus_sections_info/fast:
	$(MAKE) -f esp-idf/freemodbus/CMakeFiles/idf_component_freemodbus_sections_info.dir/build.make esp-idf/freemodbus/CMakeFiles/idf_component_freemodbus_sections_info.dir/build
.PHONY : idf_component_freemodbus_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_json_sections_info

# Build rule for target.
idf_component_json_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_json_sections_info
.PHONY : idf_component_json_sections_info

# fast build rule for target.
idf_component_json_sections_info/fast:
	$(MAKE) -f esp-idf/json/CMakeFiles/idf_component_json_sections_info.dir/build.make esp-idf/json/CMakeFiles/idf_component_json_sections_info.dir/build
.PHONY : idf_component_json_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_json

# Build rule for target.
idf_component_json: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_json
.PHONY : idf_component_json

# fast build rule for target.
idf_component_json/fast:
	$(MAKE) -f esp-idf/json/CMakeFiles/idf_component_json.dir/build.make esp-idf/json/CMakeFiles/idf_component_json.dir/build
.PHONY : idf_component_json/fast

#=============================================================================
# Target rules for targets named idf_component_libsodium_sections_info

# Build rule for target.
idf_component_libsodium_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_libsodium_sections_info
.PHONY : idf_component_libsodium_sections_info

# fast build rule for target.
idf_component_libsodium_sections_info/fast:
	$(MAKE) -f esp-idf/libsodium/CMakeFiles/idf_component_libsodium_sections_info.dir/build.make esp-idf/libsodium/CMakeFiles/idf_component_libsodium_sections_info.dir/build
.PHONY : idf_component_libsodium_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_libsodium

# Build rule for target.
idf_component_libsodium: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_libsodium
.PHONY : idf_component_libsodium

# fast build rule for target.
idf_component_libsodium/fast:
	$(MAKE) -f esp-idf/libsodium/CMakeFiles/idf_component_libsodium.dir/build.make esp-idf/libsodium/CMakeFiles/idf_component_libsodium.dir/build
.PHONY : idf_component_libsodium/fast

#=============================================================================
# Target rules for targets named idf_component_mdns

# Build rule for target.
idf_component_mdns: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_mdns
.PHONY : idf_component_mdns

# fast build rule for target.
idf_component_mdns/fast:
	$(MAKE) -f esp-idf/mdns/CMakeFiles/idf_component_mdns.dir/build.make esp-idf/mdns/CMakeFiles/idf_component_mdns.dir/build
.PHONY : idf_component_mdns/fast

#=============================================================================
# Target rules for targets named idf_component_mdns_sections_info

# Build rule for target.
idf_component_mdns_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_mdns_sections_info
.PHONY : idf_component_mdns_sections_info

# fast build rule for target.
idf_component_mdns_sections_info/fast:
	$(MAKE) -f esp-idf/mdns/CMakeFiles/idf_component_mdns_sections_info.dir/build.make esp-idf/mdns/CMakeFiles/idf_component_mdns_sections_info.dir/build
.PHONY : idf_component_mdns_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_mqtt

# Build rule for target.
idf_component_mqtt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_mqtt
.PHONY : idf_component_mqtt

# fast build rule for target.
idf_component_mqtt/fast:
	$(MAKE) -f esp-idf/mqtt/CMakeFiles/idf_component_mqtt.dir/build.make esp-idf/mqtt/CMakeFiles/idf_component_mqtt.dir/build
.PHONY : idf_component_mqtt/fast

#=============================================================================
# Target rules for targets named idf_component_mqtt_sections_info

# Build rule for target.
idf_component_mqtt_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_mqtt_sections_info
.PHONY : idf_component_mqtt_sections_info

# fast build rule for target.
idf_component_mqtt_sections_info/fast:
	$(MAKE) -f esp-idf/mqtt/CMakeFiles/idf_component_mqtt_sections_info.dir/build.make esp-idf/mqtt/CMakeFiles/idf_component_mqtt_sections_info.dir/build
.PHONY : idf_component_mqtt_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_protobuf-c

# Build rule for target.
idf_component_protobuf-c: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_protobuf-c
.PHONY : idf_component_protobuf-c

# fast build rule for target.
idf_component_protobuf-c/fast:
	$(MAKE) -f esp-idf/protobuf-c/CMakeFiles/idf_component_protobuf-c.dir/build.make esp-idf/protobuf-c/CMakeFiles/idf_component_protobuf-c.dir/build
.PHONY : idf_component_protobuf-c/fast

#=============================================================================
# Target rules for targets named idf_component_protobuf-c_sections_info

# Build rule for target.
idf_component_protobuf-c_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_protobuf-c_sections_info
.PHONY : idf_component_protobuf-c_sections_info

# fast build rule for target.
idf_component_protobuf-c_sections_info/fast:
	$(MAKE) -f esp-idf/protobuf-c/CMakeFiles/idf_component_protobuf-c_sections_info.dir/build.make esp-idf/protobuf-c/CMakeFiles/idf_component_protobuf-c_sections_info.dir/build
.PHONY : idf_component_protobuf-c_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_protocomm_sections_info

# Build rule for target.
idf_component_protocomm_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_protocomm_sections_info
.PHONY : idf_component_protocomm_sections_info

# fast build rule for target.
idf_component_protocomm_sections_info/fast:
	$(MAKE) -f esp-idf/protocomm/CMakeFiles/idf_component_protocomm_sections_info.dir/build.make esp-idf/protocomm/CMakeFiles/idf_component_protocomm_sections_info.dir/build
.PHONY : idf_component_protocomm_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_protocomm

# Build rule for target.
idf_component_protocomm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_protocomm
.PHONY : idf_component_protocomm

# fast build rule for target.
idf_component_protocomm/fast:
	$(MAKE) -f esp-idf/protocomm/CMakeFiles/idf_component_protocomm.dir/build.make esp-idf/protocomm/CMakeFiles/idf_component_protocomm.dir/build
.PHONY : idf_component_protocomm/fast

#=============================================================================
# Target rules for targets named idf_component_spiffs_sections_info

# Build rule for target.
idf_component_spiffs_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_spiffs_sections_info
.PHONY : idf_component_spiffs_sections_info

# fast build rule for target.
idf_component_spiffs_sections_info/fast:
	$(MAKE) -f esp-idf/spiffs/CMakeFiles/idf_component_spiffs_sections_info.dir/build.make esp-idf/spiffs/CMakeFiles/idf_component_spiffs_sections_info.dir/build
.PHONY : idf_component_spiffs_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_spiffs

# Build rule for target.
idf_component_spiffs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_spiffs
.PHONY : idf_component_spiffs

# fast build rule for target.
idf_component_spiffs/fast:
	$(MAKE) -f esp-idf/spiffs/CMakeFiles/idf_component_spiffs.dir/build.make esp-idf/spiffs/CMakeFiles/idf_component_spiffs.dir/build
.PHONY : idf_component_spiffs/fast

#=============================================================================
# Target rules for targets named idf_component_ulp_sections_info

# Build rule for target.
idf_component_ulp_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_ulp_sections_info
.PHONY : idf_component_ulp_sections_info

# fast build rule for target.
idf_component_ulp_sections_info/fast:
	$(MAKE) -f esp-idf/ulp/CMakeFiles/idf_component_ulp_sections_info.dir/build.make esp-idf/ulp/CMakeFiles/idf_component_ulp_sections_info.dir/build
.PHONY : idf_component_ulp_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_ulp

# Build rule for target.
idf_component_ulp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_ulp
.PHONY : idf_component_ulp

# fast build rule for target.
idf_component_ulp/fast:
	$(MAKE) -f esp-idf/ulp/CMakeFiles/idf_component_ulp.dir/build.make esp-idf/ulp/CMakeFiles/idf_component_ulp.dir/build
.PHONY : idf_component_ulp/fast

#=============================================================================
# Target rules for targets named idf_component_unity_sections_info

# Build rule for target.
idf_component_unity_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_unity_sections_info
.PHONY : idf_component_unity_sections_info

# fast build rule for target.
idf_component_unity_sections_info/fast:
	$(MAKE) -f esp-idf/unity/CMakeFiles/idf_component_unity_sections_info.dir/build.make esp-idf/unity/CMakeFiles/idf_component_unity_sections_info.dir/build
.PHONY : idf_component_unity_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_unity

# Build rule for target.
idf_component_unity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_unity
.PHONY : idf_component_unity

# fast build rule for target.
idf_component_unity/fast:
	$(MAKE) -f esp-idf/unity/CMakeFiles/idf_component_unity.dir/build.make esp-idf/unity/CMakeFiles/idf_component_unity.dir/build
.PHONY : idf_component_unity/fast

#=============================================================================
# Target rules for targets named idf_component_wifi_provisioning_sections_info

# Build rule for target.
idf_component_wifi_provisioning_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_wifi_provisioning_sections_info
.PHONY : idf_component_wifi_provisioning_sections_info

# fast build rule for target.
idf_component_wifi_provisioning_sections_info/fast:
	$(MAKE) -f esp-idf/wifi_provisioning/CMakeFiles/idf_component_wifi_provisioning_sections_info.dir/build.make esp-idf/wifi_provisioning/CMakeFiles/idf_component_wifi_provisioning_sections_info.dir/build
.PHONY : idf_component_wifi_provisioning_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_wifi_provisioning

# Build rule for target.
idf_component_wifi_provisioning: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_wifi_provisioning
.PHONY : idf_component_wifi_provisioning

# fast build rule for target.
idf_component_wifi_provisioning/fast:
	$(MAKE) -f esp-idf/wifi_provisioning/CMakeFiles/idf_component_wifi_provisioning.dir/build.make esp-idf/wifi_provisioning/CMakeFiles/idf_component_wifi_provisioning.dir/build
.PHONY : idf_component_wifi_provisioning/fast

#=============================================================================
# Target rules for targets named idf_component_main_sections_info

# Build rule for target.
idf_component_main_sections_info: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_main_sections_info
.PHONY : idf_component_main_sections_info

# fast build rule for target.
idf_component_main_sections_info/fast:
	$(MAKE) -f esp-idf/main/CMakeFiles/idf_component_main_sections_info.dir/build.make esp-idf/main/CMakeFiles/idf_component_main_sections_info.dir/build
.PHONY : idf_component_main_sections_info/fast

#=============================================================================
# Target rules for targets named idf_component_main

# Build rule for target.
idf_component_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 idf_component_main
.PHONY : idf_component_main

# fast build rule for target.
idf_component_main/fast:
	$(MAKE) -f esp-idf/main/CMakeFiles/idf_component_main.dir/build.make esp-idf/main/CMakeFiles/idf_component_main.dir/build
.PHONY : idf_component_main/fast

dummy_main_src.obj: dummy_main_src.c.obj

.PHONY : dummy_main_src.obj

# target to build an object file
dummy_main_src.c.obj:
	$(MAKE) -f CMakeFiles/volkhin_nixie_timer.elf.dir/build.make CMakeFiles/volkhin_nixie_timer.elf.dir/dummy_main_src.c.obj
.PHONY : dummy_main_src.c.obj

dummy_main_src.i: dummy_main_src.c.i

.PHONY : dummy_main_src.i

# target to preprocess a source file
dummy_main_src.c.i:
	$(MAKE) -f CMakeFiles/volkhin_nixie_timer.elf.dir/build.make CMakeFiles/volkhin_nixie_timer.elf.dir/dummy_main_src.c.i
.PHONY : dummy_main_src.c.i

dummy_main_src.s: dummy_main_src.c.s

.PHONY : dummy_main_src.s

# target to generate assembly for a file
dummy_main_src.c.s:
	$(MAKE) -f CMakeFiles/volkhin_nixie_timer.elf.dir/build.make CMakeFiles/volkhin_nixie_timer.elf.dir/dummy_main_src.c.s
.PHONY : dummy_main_src.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... size-files"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... size-components"
	@echo "... volkhin_nixie_timer.elf"
	@echo "... size"
	@echo "... dummy_main_src"
	@echo "... edit_cache"
	@echo "... mconf-idf"
	@echo "... bootloader-flash"
	@echo "... app-flash"
	@echo "... flash"
	@echo "... app"
	@echo "... ldgen"
	@echo "... bootloader"
	@echo "... gen_secure_boot_signing_key"
	@echo "... ldgen_section_infos"
	@echo "... confserver"
	@echo "... menuconfig"
	@echo "... idf_component_soc_sections_info"
	@echo "... idf_component_soc"
	@echo "... idf_component_log"
	@echo "... idf_component_log_sections_info"
	@echo "... idf_component_heap_sections_info"
	@echo "... idf_component_heap"
	@echo "... idf_component_xtensa-debug-module"
	@echo "... idf_component_xtensa-debug-module_sections_info"
	@echo "... idf_component_app_trace_sections_info"
	@echo "... idf_component_app_trace"
	@echo "... idf_component_freertos_sections_info"
	@echo "... idf_component_freertos"
	@echo "... idf_component_vfs_sections_info"
	@echo "... idf_component_vfs"
	@echo "... idf_component_newlib"
	@echo "... idf_component_newlib_sections_info"
	@echo "... idf_component_esp_ringbuf"
	@echo "... idf_component_esp_ringbuf_sections_info"
	@echo "... idf_component_driver_sections_info"
	@echo "... idf_component_driver"
	@echo "... idf_component_esp_event_sections_info"
	@echo "... idf_component_esp_event"
	@echo "... idf_component_ethernet_sections_info"
	@echo "... idf_component_ethernet"
	@echo "... idf_component_mbedtls_sections_info"
	@echo "... idf_component_mbedtls"
	@echo "... apidoc"
	@echo "... lib"
	@echo "... mbedcrypto"
	@echo "... mbedx509"
	@echo "... mbedtls"
	@echo "... idf_component_micro-ecc_sections_info"
	@echo "... idf_component_micro-ecc"
	@echo "... idf_component_bootloader_support_sections_info"
	@echo "... idf_component_bootloader_support"
	@echo "... partition_table"
	@echo "... erase_otadata"
	@echo "... read_otadata"
	@echo "... idf_component_app_update_sections_info"
	@echo "... idf_component_app_update"
	@echo "... idf_component_spi_flash"
	@echo "... idf_component_spi_flash_sections_info"
	@echo "... idf_component_nvs_flash"
	@echo "... idf_component_nvs_flash_sections_info"
	@echo "... idf_component_lwip_sections_info"
	@echo "... idf_component_lwip"
	@echo "... idf_component_tcpip_adapter_sections_info"
	@echo "... idf_component_tcpip_adapter"
	@echo "... idf_component_pthread_sections_info"
	@echo "... idf_component_pthread"
	@echo "... idf_component_smartconfig_ack"
	@echo "... idf_component_smartconfig_ack_sections_info"
	@echo "... idf_component_wpa_supplicant_sections_info"
	@echo "... idf_component_wpa_supplicant"
	@echo "... idf_component_esp32"
	@echo "... ldgen_esp32.common.ld_script"
	@echo "... idf_component_esp32_sections_info"
	@echo "... esp32_linker_script"
	@echo "... idf_component_cxx_sections_info"
	@echo "... idf_component_cxx"
	@echo "... idf_component_asio_sections_info"
	@echo "... idf_component_asio"
	@echo "... idf_component_jsmn_sections_info"
	@echo "... idf_component_jsmn"
	@echo "... idf_component_bt"
	@echo "... idf_component_bt_sections_info"
	@echo "... idf_component_coap_sections_info"
	@echo "... idf_component_coap"
	@echo "... idf_component_console_sections_info"
	@echo "... idf_component_console"
	@echo "... idf_component_nghttp_sections_info"
	@echo "... idf_component_nghttp"
	@echo "... idf_component_esp-tls_sections_info"
	@echo "... idf_component_esp-tls"
	@echo "... idf_component_esp_adc_cal"
	@echo "... idf_component_esp_adc_cal_sections_info"
	@echo "... idf_component_tcp_transport"
	@echo "... idf_component_tcp_transport_sections_info"
	@echo "... idf_component_esp_http_client_sections_info"
	@echo "... idf_component_esp_http_client"
	@echo "... idf_component_esp_http_server"
	@echo "... idf_component_esp_http_server_sections_info"
	@echo "... idf_component_esp_https_ota_sections_info"
	@echo "... idf_component_esp_https_ota"
	@echo "... idf_component_openssl_sections_info"
	@echo "... idf_component_openssl"
	@echo "... idf_component_esp_https_server_sections_info"
	@echo "... idf_component_esp_https_server"
	@echo "... idf_component_expat_sections_info"
	@echo "... idf_component_expat"
	@echo "... idf_component_wear_levelling_sections_info"
	@echo "... idf_component_wear_levelling"
	@echo "... idf_component_sdmmc_sections_info"
	@echo "... idf_component_sdmmc"
	@echo "... idf_component_fatfs"
	@echo "... idf_component_fatfs_sections_info"
	@echo "... idf_component_freemodbus"
	@echo "... idf_component_freemodbus_sections_info"
	@echo "... idf_component_json_sections_info"
	@echo "... idf_component_json"
	@echo "... idf_component_libsodium_sections_info"
	@echo "... idf_component_libsodium"
	@echo "... idf_component_mdns"
	@echo "... idf_component_mdns_sections_info"
	@echo "... idf_component_mqtt"
	@echo "... idf_component_mqtt_sections_info"
	@echo "... idf_component_protobuf-c"
	@echo "... idf_component_protobuf-c_sections_info"
	@echo "... idf_component_protocomm_sections_info"
	@echo "... idf_component_protocomm"
	@echo "... idf_component_spiffs_sections_info"
	@echo "... idf_component_spiffs"
	@echo "... idf_component_ulp_sections_info"
	@echo "... idf_component_ulp"
	@echo "... idf_component_unity_sections_info"
	@echo "... idf_component_unity"
	@echo "... idf_component_wifi_provisioning_sections_info"
	@echo "... idf_component_wifi_provisioning"
	@echo "... idf_component_main_sections_info"
	@echo "... idf_component_main"
	@echo "... dummy_main_src.obj"
	@echo "... dummy_main_src.i"
	@echo "... dummy_main_src.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

