/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Sun Mar  3 23:12:07 2019. */

#include "alertsDeleteAlertDirectivePayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t alerts_DeleteAlertDirectivePayloadProto_fields[2] = {
    PB_FIELD(  1, STRING  , SINGULAR, STATIC  , FIRST, alerts_DeleteAlertDirectivePayloadProto, token, token, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
