/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Sun Mar  3 23:12:07 2019. */

#ifndef PB_ALERTS_ALERTSDELETEALERTDIRECTIVE_PB_H_INCLUDED
#define PB_ALERTS_ALERTSDELETEALERTDIRECTIVE_PB_H_INCLUDED
#include <pb.h>

#include "directiveHeader.pb.h"

#include "alertsDeleteAlertDirectivePayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _alerts_DeleteAlertDirectiveProto_Directive {
    header_DirectiveHeaderProto header;
    alerts_DeleteAlertDirectivePayloadProto payload;
/* @@protoc_insertion_point(struct:alerts_DeleteAlertDirectiveProto_Directive) */
} alerts_DeleteAlertDirectiveProto_Directive;

typedef struct _alerts_DeleteAlertDirectiveProto {
    alerts_DeleteAlertDirectiveProto_Directive directive;
/* @@protoc_insertion_point(struct:alerts_DeleteAlertDirectiveProto) */
} alerts_DeleteAlertDirectiveProto;

/* Default values for struct fields */

/* Initializer values for message structs */
#define alerts_DeleteAlertDirectiveProto_init_default {alerts_DeleteAlertDirectiveProto_Directive_init_default}
#define alerts_DeleteAlertDirectiveProto_Directive_init_default {header_DirectiveHeaderProto_init_default, alerts_DeleteAlertDirectivePayloadProto_init_default}
#define alerts_DeleteAlertDirectiveProto_init_zero {alerts_DeleteAlertDirectiveProto_Directive_init_zero}
#define alerts_DeleteAlertDirectiveProto_Directive_init_zero {header_DirectiveHeaderProto_init_zero, alerts_DeleteAlertDirectivePayloadProto_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define alerts_DeleteAlertDirectiveProto_Directive_payload_tag 2
#define alerts_DeleteAlertDirectiveProto_Directive_header_tag 1
#define alerts_DeleteAlertDirectiveProto_directive_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t alerts_DeleteAlertDirectiveProto_fields[2];
extern const pb_field_t alerts_DeleteAlertDirectiveProto_Directive_fields[3];

/* Maximum encoded size of messages (where known) */
#define alerts_DeleteAlertDirectiveProto_size    (80 + header_DirectiveHeaderProto_size)
#define alerts_DeleteAlertDirectiveProto_Directive_size (74 + header_DirectiveHeaderProto_size)

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ALERTSDELETEALERTDIRECTIVE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
