/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Sun Mar  3 23:12:08 2019. */

#ifndef PB_ALERTS_ALERTSSETALERTDIRECTIVEPAYLOAD_PB_H_INCLUDED
#define PB_ALERTS_ALERTSSETALERTDIRECTIVEPAYLOAD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _alerts_SetAlertDirectivePayloadProto_Assets {
    char assetId[32];
    char url[64];
/* @@protoc_insertion_point(struct:alerts_SetAlertDirectivePayloadProto_Assets) */
} alerts_SetAlertDirectivePayloadProto_Assets;

typedef struct _alerts_SetAlertDirectivePayloadProto {
    char token[64];
    char type[32];
    char scheduledTime[64];
    pb_size_t assets_count;
    alerts_SetAlertDirectivePayloadProto_Assets assets[1];
    pb_size_t assetPlayOrder_count;
    char assetPlayOrder[1][16];
    char backgroundAlertAsset[16];
    int32_t loopCount;
    int32_t loopPauseInMilliSeconds;
/* @@protoc_insertion_point(struct:alerts_SetAlertDirectivePayloadProto) */
} alerts_SetAlertDirectivePayloadProto;

/* Default values for struct fields */

/* Initializer values for message structs */
#define alerts_SetAlertDirectivePayloadProto_init_default {"", "", "", 0, {alerts_SetAlertDirectivePayloadProto_Assets_init_default}, 0, {""}, "", 0, 0}
#define alerts_SetAlertDirectivePayloadProto_Assets_init_default {"", ""}
#define alerts_SetAlertDirectivePayloadProto_init_zero {"", "", "", 0, {alerts_SetAlertDirectivePayloadProto_Assets_init_zero}, 0, {""}, "", 0, 0}
#define alerts_SetAlertDirectivePayloadProto_Assets_init_zero {"", ""}

/* Field tags (for use in manual encoding/decoding) */
#define alerts_SetAlertDirectivePayloadProto_Assets_assetId_tag 1
#define alerts_SetAlertDirectivePayloadProto_Assets_url_tag 2
#define alerts_SetAlertDirectivePayloadProto_assetPlayOrder_tag 5
#define alerts_SetAlertDirectivePayloadProto_loopPauseInMilliSeconds_tag 8
#define alerts_SetAlertDirectivePayloadProto_scheduledTime_tag 3
#define alerts_SetAlertDirectivePayloadProto_assets_tag 4
#define alerts_SetAlertDirectivePayloadProto_loopCount_tag 7
#define alerts_SetAlertDirectivePayloadProto_backgroundAlertAsset_tag 6
#define alerts_SetAlertDirectivePayloadProto_type_tag 2
#define alerts_SetAlertDirectivePayloadProto_token_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t alerts_SetAlertDirectivePayloadProto_fields[9];
extern const pb_field_t alerts_SetAlertDirectivePayloadProto_Assets_fields[3];

/* Maximum encoded size of messages (where known) */
#define alerts_SetAlertDirectivePayloadProto_size 328
#define alerts_SetAlertDirectivePayloadProto_Assets_size 100

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ALERTSSETALERTDIRECTIVEPAYLOAD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
