/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Sun Mar  3 23:12:07 2019. */

#ifndef PB_ALERTS_ALERTSDELETEALERTDIRECTIVEPAYLOAD_PB_H_INCLUDED
#define PB_ALERTS_ALERTSDELETEALERTDIRECTIVEPAYLOAD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _alerts_DeleteAlertDirectivePayloadProto {
    char token[64];
/* @@protoc_insertion_point(struct:alerts_DeleteAlertDirectivePayloadProto) */
} alerts_DeleteAlertDirectivePayloadProto;

/* Default values for struct fields */

/* Initializer values for message structs */
#define alerts_DeleteAlertDirectivePayloadProto_init_default {""}
#define alerts_DeleteAlertDirectivePayloadProto_init_zero {""}

/* Field tags (for use in manual encoding/decoding) */
#define alerts_DeleteAlertDirectivePayloadProto_token_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t alerts_DeleteAlertDirectivePayloadProto_fields[2];

/* Maximum encoded size of messages (where known) */
#define alerts_DeleteAlertDirectivePayloadProto_size 66

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ALERTSDELETEALERTDIRECTIVEPAYLOAD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
