/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Sun Mar  3 23:12:08 2019. */

#ifndef PB_ALERTS_ALERTSSETALERTDIRECTIVE_PB_H_INCLUDED
#define PB_ALERTS_ALERTSSETALERTDIRECTIVE_PB_H_INCLUDED
#include <pb.h>

#include "directiveHeader.pb.h"

#include "alertsSetAlertDirectivePayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _alerts_SetAlertDirectiveProto_Directive {
    header_DirectiveHeaderProto header;
    alerts_SetAlertDirectivePayloadProto payload;
/* @@protoc_insertion_point(struct:alerts_SetAlertDirectiveProto_Directive) */
} alerts_SetAlertDirectiveProto_Directive;

typedef struct _alerts_SetAlertDirectiveProto {
    alerts_SetAlertDirectiveProto_Directive directive;
/* @@protoc_insertion_point(struct:alerts_SetAlertDirectiveProto) */
} alerts_SetAlertDirectiveProto;

/* Default values for struct fields */

/* Initializer values for message structs */
#define alerts_SetAlertDirectiveProto_init_default {alerts_SetAlertDirectiveProto_Directive_init_default}
#define alerts_SetAlertDirectiveProto_Directive_init_default {header_DirectiveHeaderProto_init_default, alerts_SetAlertDirectivePayloadProto_init_default}
#define alerts_SetAlertDirectiveProto_init_zero  {alerts_SetAlertDirectiveProto_Directive_init_zero}
#define alerts_SetAlertDirectiveProto_Directive_init_zero {header_DirectiveHeaderProto_init_zero, alerts_SetAlertDirectivePayloadProto_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define alerts_SetAlertDirectiveProto_Directive_payload_tag 2
#define alerts_SetAlertDirectiveProto_Directive_header_tag 1
#define alerts_SetAlertDirectiveProto_directive_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t alerts_SetAlertDirectiveProto_fields[2];
extern const pb_field_t alerts_SetAlertDirectiveProto_Directive_fields[3];

/* Maximum encoded size of messages (where known) */
#define alerts_SetAlertDirectiveProto_size       (343 + header_DirectiveHeaderProto_size)
#define alerts_SetAlertDirectiveProto_Directive_size (337 + header_DirectiveHeaderProto_size)

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ALERTSSETALERTDIRECTIVE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
