/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Sun Mar  3 23:12:09 2019. */

#include "alexaGadgetMusicDataTempoDirectivePayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t alexaGadgetMusicData_TempoDirectivePayloadProto_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, alexaGadgetMusicData_TempoDirectivePayloadProto, playerOffsetInMilliSeconds, playerOffsetInMilliSeconds, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, STATIC  , OTHER, alexaGadgetMusicData_TempoDirectivePayloadProto, tempoData, playerOffsetInMilliSeconds, &alexaGadgetMusicData_TempoDirectivePayloadProto_TempoData_fields),
    PB_LAST_FIELD
};

const pb_field_t alexaGadgetMusicData_TempoDirectivePayloadProto_TempoData_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, alexaGadgetMusicData_TempoDirectivePayloadProto_TempoData, value, value, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, alexaGadgetMusicData_TempoDirectivePayloadProto_TempoData, startOffsetInMilliSeconds, value, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(alexaGadgetMusicData_TempoDirectivePayloadProto, tempoData[0]) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_alexaGadgetMusicData_TempoDirectivePayloadProto_alexaGadgetMusicData_TempoDirectivePayloadProto_TempoData)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(alexaGadgetMusicData_TempoDirectivePayloadProto, tempoData[0]) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_alexaGadgetMusicData_TempoDirectivePayloadProto_alexaGadgetMusicData_TempoDirectivePayloadProto_TempoData)
#endif


/* @@protoc_insertion_point(eof) */
