/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Sun Mar  3 23:12:08 2019. */

#ifndef PB_ALEXAGADGETSPEECHDATA_ALEXAGADGETSPEECHDATASPEECHMARKSDIRECTIVEPAYLOAD_PB_H_INCLUDED
#define PB_ALEXAGADGETSPEECHDATA_ALEXAGADGETSPEECHDATASPEECHMARKSDIRECTIVEPAYLOAD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto_SpeechmarksData {
    char value[10];
    char type[10];
    int32_t startOffsetInMilliSeconds;
/* @@protoc_insertion_point(struct:alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto_SpeechmarksData) */
} alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto_SpeechmarksData;

typedef struct _alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto {
    int32_t playerOffsetInMilliSeconds;
    pb_size_t speechmarksData_count;
    alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto_SpeechmarksData speechmarksData[1];
/* @@protoc_insertion_point(struct:alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto) */
} alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto;

/* Default values for struct fields */

/* Initializer values for message structs */
#define alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto_init_default {0, 0, {alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto_SpeechmarksData_init_default}}
#define alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto_SpeechmarksData_init_default {"", "", 0}
#define alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto_init_zero {0, 0, {alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto_SpeechmarksData_init_zero}}
#define alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto_SpeechmarksData_init_zero {"", "", 0}

/* Field tags (for use in manual encoding/decoding) */
#define alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto_SpeechmarksData_startOffsetInMilliSeconds_tag 3
#define alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto_SpeechmarksData_type_tag 2
#define alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto_SpeechmarksData_value_tag 1
#define alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto_speechmarksData_tag 2
#define alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto_playerOffsetInMilliSeconds_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto_fields[3];
extern const pb_field_t alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto_SpeechmarksData_fields[4];

/* Maximum encoded size of messages (where known) */
#define alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto_size 49
#define alexaGadgetSpeechData_SpeechmarksDirectivePayloadProto_SpeechmarksData_size 35

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ALEXAGADGETSPEECHDATASPEECHMARKSDIRECTIVEPAYLOAD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
