/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Sun Mar  3 23:12:08 2019. */

#ifndef PB_ALEXAGADGETSTATELISTENER_ALEXAGADGETSTATELISTENERSTATEUPDATEDIRECTIVE_PB_H_INCLUDED
#define PB_ALEXAGADGETSTATELISTENER_ALEXAGADGETSTATELISTENERSTATEUPDATEDIRECTIVE_PB_H_INCLUDED
#include <pb.h>

#include "directiveHeader.pb.h"

#include "alexaGadgetStateListenerStateUpdateDirectivePayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _alexaGadgetStateListener_StateUpdateDirectiveProto_Directive {
    header_DirectiveHeaderProto header;
    alexaGadgetStateListener_StateUpdateDirectivePayloadProto payload;
/* @@protoc_insertion_point(struct:alexaGadgetStateListener_StateUpdateDirectiveProto_Directive) */
} alexaGadgetStateListener_StateUpdateDirectiveProto_Directive;

typedef struct _alexaGadgetStateListener_StateUpdateDirectiveProto {
    alexaGadgetStateListener_StateUpdateDirectiveProto_Directive directive;
/* @@protoc_insertion_point(struct:alexaGadgetStateListener_StateUpdateDirectiveProto) */
} alexaGadgetStateListener_StateUpdateDirectiveProto;

/* Default values for struct fields */

/* Initializer values for message structs */
#define alexaGadgetStateListener_StateUpdateDirectiveProto_init_default {alexaGadgetStateListener_StateUpdateDirectiveProto_Directive_init_default}
#define alexaGadgetStateListener_StateUpdateDirectiveProto_Directive_init_default {header_DirectiveHeaderProto_init_default, alexaGadgetStateListener_StateUpdateDirectivePayloadProto_init_default}
#define alexaGadgetStateListener_StateUpdateDirectiveProto_init_zero {alexaGadgetStateListener_StateUpdateDirectiveProto_Directive_init_zero}
#define alexaGadgetStateListener_StateUpdateDirectiveProto_Directive_init_zero {header_DirectiveHeaderProto_init_zero, alexaGadgetStateListener_StateUpdateDirectivePayloadProto_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define alexaGadgetStateListener_StateUpdateDirectiveProto_Directive_payload_tag 2
#define alexaGadgetStateListener_StateUpdateDirectiveProto_Directive_header_tag 1
#define alexaGadgetStateListener_StateUpdateDirectiveProto_directive_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t alexaGadgetStateListener_StateUpdateDirectiveProto_fields[2];
extern const pb_field_t alexaGadgetStateListener_StateUpdateDirectiveProto_Directive_fields[3];

/* Maximum encoded size of messages (where known) */
#define alexaGadgetStateListener_StateUpdateDirectiveProto_size (365 + header_DirectiveHeaderProto_size)
#define alexaGadgetStateListener_StateUpdateDirectiveProto_Directive_size (359 + header_DirectiveHeaderProto_size)

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ALEXAGADGETSTATELISTENERSTATEUPDATEDIRECTIVE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
