/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Sun Mar  3 23:12:09 2019. */

#ifndef PB_ALEXADISCOVERY_ALEXADISCOVERYDISCOVERDIRECTIVEPAYLOAD_PB_H_INCLUDED
#define PB_ALEXADISCOVERY_ALEXADISCOVERYDISCOVERDIRECTIVEPAYLOAD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _alexaDiscovery_DiscoverDirectivePayloadProto_Scope {
    char type[32];
    char token[32];
/* @@protoc_insertion_point(struct:alexaDiscovery_DiscoverDirectivePayloadProto_Scope) */
} alexaDiscovery_DiscoverDirectivePayloadProto_Scope;

typedef struct _alexaDiscovery_DiscoverDirectivePayloadProto {
    alexaDiscovery_DiscoverDirectivePayloadProto_Scope scope;
/* @@protoc_insertion_point(struct:alexaDiscovery_DiscoverDirectivePayloadProto) */
} alexaDiscovery_DiscoverDirectivePayloadProto;

/* Default values for struct fields */

/* Initializer values for message structs */
#define alexaDiscovery_DiscoverDirectivePayloadProto_init_default {alexaDiscovery_DiscoverDirectivePayloadProto_Scope_init_default}
#define alexaDiscovery_DiscoverDirectivePayloadProto_Scope_init_default {"", ""}
#define alexaDiscovery_DiscoverDirectivePayloadProto_init_zero {alexaDiscovery_DiscoverDirectivePayloadProto_Scope_init_zero}
#define alexaDiscovery_DiscoverDirectivePayloadProto_Scope_init_zero {"", ""}

/* Field tags (for use in manual encoding/decoding) */
#define alexaDiscovery_DiscoverDirectivePayloadProto_Scope_type_tag 1
#define alexaDiscovery_DiscoverDirectivePayloadProto_Scope_token_tag 2
#define alexaDiscovery_DiscoverDirectivePayloadProto_scope_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t alexaDiscovery_DiscoverDirectivePayloadProto_fields[2];
extern const pb_field_t alexaDiscovery_DiscoverDirectivePayloadProto_Scope_fields[3];

/* Maximum encoded size of messages (where known) */
#define alexaDiscovery_DiscoverDirectivePayloadProto_size 70
#define alexaDiscovery_DiscoverDirectivePayloadProto_Scope_size 68

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ALEXADISCOVERYDISCOVERDIRECTIVEPAYLOAD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
