/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Sun Mar  3 23:12:09 2019. */

#ifndef PB_ALEXADISCOVERY_ALEXADISCOVERYDISCOVERDIRECTIVE_PB_H_INCLUDED
#define PB_ALEXADISCOVERY_ALEXADISCOVERYDISCOVERDIRECTIVE_PB_H_INCLUDED
#include <pb.h>

#include "directiveHeader.pb.h"

#include "alexaDiscoveryDiscoverDirectivePayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _alexaDiscovery_DiscoverDirectiveProto_Directive {
    header_DirectiveHeaderProto header;
    alexaDiscovery_DiscoverDirectivePayloadProto payload;
/* @@protoc_insertion_point(struct:alexaDiscovery_DiscoverDirectiveProto_Directive) */
} alexaDiscovery_DiscoverDirectiveProto_Directive;

typedef struct _alexaDiscovery_DiscoverDirectiveProto {
    alexaDiscovery_DiscoverDirectiveProto_Directive directive;
/* @@protoc_insertion_point(struct:alexaDiscovery_DiscoverDirectiveProto) */
} alexaDiscovery_DiscoverDirectiveProto;

/* Default values for struct fields */

/* Initializer values for message structs */
#define alexaDiscovery_DiscoverDirectiveProto_init_default {alexaDiscovery_DiscoverDirectiveProto_Directive_init_default}
#define alexaDiscovery_DiscoverDirectiveProto_Directive_init_default {header_DirectiveHeaderProto_init_default, alexaDiscovery_DiscoverDirectivePayloadProto_init_default}
#define alexaDiscovery_DiscoverDirectiveProto_init_zero {alexaDiscovery_DiscoverDirectiveProto_Directive_init_zero}
#define alexaDiscovery_DiscoverDirectiveProto_Directive_init_zero {header_DirectiveHeaderProto_init_zero, alexaDiscovery_DiscoverDirectivePayloadProto_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define alexaDiscovery_DiscoverDirectiveProto_Directive_payload_tag 2
#define alexaDiscovery_DiscoverDirectiveProto_Directive_header_tag 1
#define alexaDiscovery_DiscoverDirectiveProto_directive_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t alexaDiscovery_DiscoverDirectiveProto_fields[2];
extern const pb_field_t alexaDiscovery_DiscoverDirectiveProto_Directive_fields[3];

/* Maximum encoded size of messages (where known) */
#define alexaDiscovery_DiscoverDirectiveProto_size (84 + header_DirectiveHeaderProto_size)
#define alexaDiscovery_DiscoverDirectiveProto_Directive_size (78 + header_DirectiveHeaderProto_size)

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ALEXADISCOVERYDISCOVERDIRECTIVE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
