/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Sun Mar  3 23:12:08 2019. */

#ifndef PB_HEADER_DIRECTIVEHEADER_PB_H_INCLUDED
#define PB_HEADER_DIRECTIVEHEADER_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _header_DirectiveHeaderProto {
    char namespace[32];
    char name[32];
    char messageId[32];
    char dialogRequestId[32];
/* @@protoc_insertion_point(struct:header_DirectiveHeaderProto) */
} header_DirectiveHeaderProto;

/* Default values for struct fields */

/* Initializer values for message structs */
#define header_DirectiveHeaderProto_init_default {"", "", "", ""}
#define header_DirectiveHeaderProto_init_zero    {"", "", "", ""}

/* Field tags (for use in manual encoding/decoding) */
#define header_DirectiveHeaderProto_namespace_tag 1
#define header_DirectiveHeaderProto_name_tag     2
#define header_DirectiveHeaderProto_messageId_tag 3
#define header_DirectiveHeaderProto_dialogRequestId_tag 4

/* Struct field encoding specification for nanopb */
extern const pb_field_t header_DirectiveHeaderProto_fields[5];

/* Maximum encoded size of messages (where known) */
#define header_DirectiveHeaderProto_size         136

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define DIRECTIVEHEADER_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
