/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Sun Mar  3 23:12:07 2019. */

#include "directiveParser.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t directive_DirectiveParserProto_fields[2] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, directive_DirectiveParserProto, directive, directive, &directive_DirectiveParserProto_Directive_fields),
    PB_LAST_FIELD
};

const pb_field_t directive_DirectiveParserProto_Directive_fields[3] = {
    PB_FIELD(  1, MESSAGE , SINGULAR, STATIC  , FIRST, directive_DirectiveParserProto_Directive, header, header, &header_DirectiveHeaderProto_fields),
    PB_FIELD(  2, BYTES   , SINGULAR, STATIC  , OTHER, directive_DirectiveParserProto_Directive, payload, header, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(directive_DirectiveParserProto, directive) < 65536 && pb_membersize(directive_DirectiveParserProto_Directive, payload) < 65536 && pb_membersize(directive_DirectiveParserProto_Directive, header) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_directive_DirectiveParserProto_directive_DirectiveParserProto_Directive)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for directive_DirectiveParserProto_Directive.payload is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
