/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Sun Mar  3 23:12:07 2019. */

#ifndef PB_DIRECTIVE_DIRECTIVEPARSER_PB_H_INCLUDED
#define PB_DIRECTIVE_DIRECTIVEPARSER_PB_H_INCLUDED
#include <pb.h>

#include "directiveHeader.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(2048) directive_DirectiveParserProto_Directive_payload_t;
typedef struct _directive_DirectiveParserProto_Directive {
    header_DirectiveHeaderProto header;
    directive_DirectiveParserProto_Directive_payload_t payload;
/* @@protoc_insertion_point(struct:directive_DirectiveParserProto_Directive) */
} directive_DirectiveParserProto_Directive;

typedef struct _directive_DirectiveParserProto {
    directive_DirectiveParserProto_Directive directive;
/* @@protoc_insertion_point(struct:directive_DirectiveParserProto) */
} directive_DirectiveParserProto;

/* Default values for struct fields */

/* Initializer values for message structs */
#define directive_DirectiveParserProto_init_default {directive_DirectiveParserProto_Directive_init_default}
#define directive_DirectiveParserProto_Directive_init_default {header_DirectiveHeaderProto_init_default, {0, {0}}}
#define directive_DirectiveParserProto_init_zero {directive_DirectiveParserProto_Directive_init_zero}
#define directive_DirectiveParserProto_Directive_init_zero {header_DirectiveHeaderProto_init_zero, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define directive_DirectiveParserProto_Directive_payload_tag 2
#define directive_DirectiveParserProto_Directive_header_tag 1
#define directive_DirectiveParserProto_directive_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t directive_DirectiveParserProto_fields[2];
extern const pb_field_t directive_DirectiveParserProto_Directive_fields[3];

/* Maximum encoded size of messages (where known) */
#define directive_DirectiveParserProto_size      (2063 + header_DirectiveHeaderProto_size)
#define directive_DirectiveParserProto_Directive_size (2057 + header_DirectiveHeaderProto_size)

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define DIRECTIVEPARSER_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
