/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Sun Mar  3 23:12:09 2019. */

#ifndef PB_NOTIFICATIONS_NOTIFICATIONSCLEARINDICATORDIRECTIVE_PB_H_INCLUDED
#define PB_NOTIFICATIONS_NOTIFICATIONSCLEARINDICATORDIRECTIVE_PB_H_INCLUDED
#include <pb.h>

#include "directiveHeader.pb.h"

#include "notificationsClearIndicatorDirectivePayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _notifications_ClearIndicatorDirectiveProto_Directive {
    header_DirectiveHeaderProto header;
    notifications_ClearIndicatorDirectivePayloadProto payload;
/* @@protoc_insertion_point(struct:notifications_ClearIndicatorDirectiveProto_Directive) */
} notifications_ClearIndicatorDirectiveProto_Directive;

typedef struct _notifications_ClearIndicatorDirectiveProto {
    notifications_ClearIndicatorDirectiveProto_Directive directive;
/* @@protoc_insertion_point(struct:notifications_ClearIndicatorDirectiveProto) */
} notifications_ClearIndicatorDirectiveProto;

/* Default values for struct fields */

/* Initializer values for message structs */
#define notifications_ClearIndicatorDirectiveProto_init_default {notifications_ClearIndicatorDirectiveProto_Directive_init_default}
#define notifications_ClearIndicatorDirectiveProto_Directive_init_default {header_DirectiveHeaderProto_init_default, notifications_ClearIndicatorDirectivePayloadProto_init_default}
#define notifications_ClearIndicatorDirectiveProto_init_zero {notifications_ClearIndicatorDirectiveProto_Directive_init_zero}
#define notifications_ClearIndicatorDirectiveProto_Directive_init_zero {header_DirectiveHeaderProto_init_zero, notifications_ClearIndicatorDirectivePayloadProto_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define notifications_ClearIndicatorDirectiveProto_Directive_payload_tag 2
#define notifications_ClearIndicatorDirectiveProto_Directive_header_tag 1
#define notifications_ClearIndicatorDirectiveProto_directive_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t notifications_ClearIndicatorDirectiveProto_fields[2];
extern const pb_field_t notifications_ClearIndicatorDirectiveProto_Directive_fields[3];

/* Maximum encoded size of messages (where known) */
#define notifications_ClearIndicatorDirectiveProto_size (14 + header_DirectiveHeaderProto_size)
#define notifications_ClearIndicatorDirectiveProto_Directive_size (8 + header_DirectiveHeaderProto_size)

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define NOTIFICATIONSCLEARINDICATORDIRECTIVE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
