/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Sun Mar  3 23:12:09 2019. */

#ifndef PB_NOTIFICATIONS_NOTIFICATIONSSETINDICATORDIRECTIVEPAYLOAD_PB_H_INCLUDED
#define PB_NOTIFICATIONS_NOTIFICATIONSSETINDICATORDIRECTIVEPAYLOAD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _notifications_SetIndicatorDirectivePayloadProto_Asset {
    char assetId[64];
    char url[64];
/* @@protoc_insertion_point(struct:notifications_SetIndicatorDirectivePayloadProto_Asset) */
} notifications_SetIndicatorDirectivePayloadProto_Asset;

typedef struct _notifications_SetIndicatorDirectivePayloadProto {
    bool persistVisualIndicator;
    bool playAudioIndicator;
    notifications_SetIndicatorDirectivePayloadProto_Asset asset;
/* @@protoc_insertion_point(struct:notifications_SetIndicatorDirectivePayloadProto) */
} notifications_SetIndicatorDirectivePayloadProto;

/* Default values for struct fields */

/* Initializer values for message structs */
#define notifications_SetIndicatorDirectivePayloadProto_init_default {0, 0, notifications_SetIndicatorDirectivePayloadProto_Asset_init_default}
#define notifications_SetIndicatorDirectivePayloadProto_Asset_init_default {"", ""}
#define notifications_SetIndicatorDirectivePayloadProto_init_zero {0, 0, notifications_SetIndicatorDirectivePayloadProto_Asset_init_zero}
#define notifications_SetIndicatorDirectivePayloadProto_Asset_init_zero {"", ""}

/* Field tags (for use in manual encoding/decoding) */
#define notifications_SetIndicatorDirectivePayloadProto_Asset_assetId_tag 1
#define notifications_SetIndicatorDirectivePayloadProto_Asset_url_tag 2
#define notifications_SetIndicatorDirectivePayloadProto_persistVisualIndicator_tag 1
#define notifications_SetIndicatorDirectivePayloadProto_playAudioIndicator_tag 2
#define notifications_SetIndicatorDirectivePayloadProto_asset_tag 3

/* Struct field encoding specification for nanopb */
extern const pb_field_t notifications_SetIndicatorDirectivePayloadProto_fields[4];
extern const pb_field_t notifications_SetIndicatorDirectivePayloadProto_Asset_fields[3];

/* Maximum encoded size of messages (where known) */
#define notifications_SetIndicatorDirectivePayloadProto_size 139
#define notifications_SetIndicatorDirectivePayloadProto_Asset_size 132

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define NOTIFICATIONSSETINDICATORDIRECTIVEPAYLOAD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
