/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Sun Mar  3 23:12:09 2019. */

#ifndef PB_NOTIFICATIONS_NOTIFICATIONSCLEARINDICATORDIRECTIVEPAYLOAD_PB_H_INCLUDED
#define PB_NOTIFICATIONS_NOTIFICATIONSCLEARINDICATORDIRECTIVEPAYLOAD_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _notifications_ClearIndicatorDirectivePayloadProto {
    char dummy_field;
/* @@protoc_insertion_point(struct:notifications_ClearIndicatorDirectivePayloadProto) */
} notifications_ClearIndicatorDirectivePayloadProto;

/* Default values for struct fields */

/* Initializer values for message structs */
#define notifications_ClearIndicatorDirectivePayloadProto_init_default {0}
#define notifications_ClearIndicatorDirectivePayloadProto_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */

/* Struct field encoding specification for nanopb */
extern const pb_field_t notifications_ClearIndicatorDirectivePayloadProto_fields[1];

/* Maximum encoded size of messages (where known) */
#define notifications_ClearIndicatorDirectivePayloadProto_size 0

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define NOTIFICATIONSCLEARINDICATORDIRECTIVEPAYLOAD_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
