/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.2 at Sun Mar  3 23:12:09 2019. */

#ifndef PB_NOTIFICATIONS_NOTIFICATIONSSETINDICATORDIRECTIVE_PB_H_INCLUDED
#define PB_NOTIFICATIONS_NOTIFICATIONSSETINDICATORDIRECTIVE_PB_H_INCLUDED
#include <pb.h>

#include "directiveHeader.pb.h"

#include "notificationsSetIndicatorDirectivePayload.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _notifications_SetIndicatorDirectiveProto_Directive {
    header_DirectiveHeaderProto header;
    notifications_SetIndicatorDirectivePayloadProto payload;
/* @@protoc_insertion_point(struct:notifications_SetIndicatorDirectiveProto_Directive) */
} notifications_SetIndicatorDirectiveProto_Directive;

typedef struct _notifications_SetIndicatorDirectiveProto {
    notifications_SetIndicatorDirectiveProto_Directive directive;
/* @@protoc_insertion_point(struct:notifications_SetIndicatorDirectiveProto) */
} notifications_SetIndicatorDirectiveProto;

/* Default values for struct fields */

/* Initializer values for message structs */
#define notifications_SetIndicatorDirectiveProto_init_default {notifications_SetIndicatorDirectiveProto_Directive_init_default}
#define notifications_SetIndicatorDirectiveProto_Directive_init_default {header_DirectiveHeaderProto_init_default, notifications_SetIndicatorDirectivePayloadProto_init_default}
#define notifications_SetIndicatorDirectiveProto_init_zero {notifications_SetIndicatorDirectiveProto_Directive_init_zero}
#define notifications_SetIndicatorDirectiveProto_Directive_init_zero {header_DirectiveHeaderProto_init_zero, notifications_SetIndicatorDirectivePayloadProto_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define notifications_SetIndicatorDirectiveProto_Directive_payload_tag 2
#define notifications_SetIndicatorDirectiveProto_Directive_header_tag 1
#define notifications_SetIndicatorDirectiveProto_directive_tag 1

/* Struct field encoding specification for nanopb */
extern const pb_field_t notifications_SetIndicatorDirectiveProto_fields[2];
extern const pb_field_t notifications_SetIndicatorDirectiveProto_Directive_fields[3];

/* Maximum encoded size of messages (where known) */
#define notifications_SetIndicatorDirectiveProto_size (154 + header_DirectiveHeaderProto_size)
#define notifications_SetIndicatorDirectiveProto_Directive_size (148 + header_DirectiveHeaderProto_size)

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define NOTIFICATIONSSETINDICATORDIRECTIVE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
